// Code generated by ent, DO NOT EDIT.

package useraffiliateadminaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldID, id))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldOperatorUserID, v))
}

// TargetUserID applies equality check predicate on the "target_user_id" field. It's identical to TargetUserIDEQ.
func TargetUserID(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldTargetUserID, v))
}

// WithdrawalID applies equality check predicate on the "withdrawal_id" field. It's identical to WithdrawalIDEQ.
func WithdrawalID(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldWithdrawalID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldAction, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldIdempotencyKey, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldOperatorUserID, v))
}

// TargetUserIDEQ applies the EQ predicate on the "target_user_id" field.
func TargetUserIDEQ(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetUserIDNEQ applies the NEQ predicate on the "target_user_id" field.
func TargetUserIDNEQ(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldTargetUserID, v))
}

// TargetUserIDIn applies the In predicate on the "target_user_id" field.
func TargetUserIDIn(vs ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldTargetUserID, vs...))
}

// TargetUserIDNotIn applies the NotIn predicate on the "target_user_id" field.
func TargetUserIDNotIn(vs ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldTargetUserID, vs...))
}

// TargetUserIDGT applies the GT predicate on the "target_user_id" field.
func TargetUserIDGT(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldTargetUserID, v))
}

// TargetUserIDGTE applies the GTE predicate on the "target_user_id" field.
func TargetUserIDGTE(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldTargetUserID, v))
}

// TargetUserIDLT applies the LT predicate on the "target_user_id" field.
func TargetUserIDLT(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldTargetUserID, v))
}

// TargetUserIDLTE applies the LTE predicate on the "target_user_id" field.
func TargetUserIDLTE(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldTargetUserID, v))
}

// TargetUserIDIsNil applies the IsNil predicate on the "target_user_id" field.
func TargetUserIDIsNil() predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIsNull(FieldTargetUserID))
}

// TargetUserIDNotNil applies the NotNil predicate on the "target_user_id" field.
func TargetUserIDNotNil() predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotNull(FieldTargetUserID))
}

// WithdrawalIDEQ applies the EQ predicate on the "withdrawal_id" field.
func WithdrawalIDEQ(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldWithdrawalID, v))
}

// WithdrawalIDNEQ applies the NEQ predicate on the "withdrawal_id" field.
func WithdrawalIDNEQ(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldWithdrawalID, v))
}

// WithdrawalIDIn applies the In predicate on the "withdrawal_id" field.
func WithdrawalIDIn(vs ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldWithdrawalID, vs...))
}

// WithdrawalIDNotIn applies the NotIn predicate on the "withdrawal_id" field.
func WithdrawalIDNotIn(vs ...int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldWithdrawalID, vs...))
}

// WithdrawalIDGT applies the GT predicate on the "withdrawal_id" field.
func WithdrawalIDGT(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldWithdrawalID, v))
}

// WithdrawalIDGTE applies the GTE predicate on the "withdrawal_id" field.
func WithdrawalIDGTE(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldWithdrawalID, v))
}

// WithdrawalIDLT applies the LT predicate on the "withdrawal_id" field.
func WithdrawalIDLT(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldWithdrawalID, v))
}

// WithdrawalIDLTE applies the LTE predicate on the "withdrawal_id" field.
func WithdrawalIDLTE(v int64) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldWithdrawalID, v))
}

// WithdrawalIDIsNil applies the IsNil predicate on the "withdrawal_id" field.
func WithdrawalIDIsNil() predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIsNull(FieldWithdrawalID))
}

// WithdrawalIDNotNil applies the NotNil predicate on the "withdrawal_id" field.
func WithdrawalIDNotNil() predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotNull(FieldWithdrawalID))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldContainsFold(FieldAction, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldContainsFold(FieldDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAffiliateAdminAudit) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAffiliateAdminAudit) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAffiliateAdminAudit) predicate.UserAffiliateAdminAudit {
	return predicate.UserAffiliateAdminAudit(sql.NotPredicates(p))
}
