// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversationevent"
	"github.com/google/uuid"
)

// ConversationEventCreate is the builder for creating a ConversationEvent entity.
type ConversationEventCreate struct {
	config
	mutation *ConversationEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSessionID sets the "session_id" field.
func (_c *ConversationEventCreate) SetSessionID(v uuid.UUID) *ConversationEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetBranchID sets the "branch_id" field.
func (_c *ConversationEventCreate) SetBranchID(v uuid.UUID) *ConversationEventCreate {
	_c.mutation.SetBranchID(v)
	return _c
}

// SetParentEventID sets the "parent_event_id" field.
func (_c *ConversationEventCreate) SetParentEventID(v int64) *ConversationEventCreate {
	_c.mutation.SetParentEventID(v)
	return _c
}

// SetNillableParentEventID sets the "parent_event_id" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableParentEventID(v *int64) *ConversationEventCreate {
	if v != nil {
		_c.SetParentEventID(*v)
	}
	return _c
}

// SetSequence sets the "sequence" field.
func (_c *ConversationEventCreate) SetSequence(v int) *ConversationEventCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *ConversationEventCreate) SetRequestID(v string) *ConversationEventCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ConversationEventCreate) SetRole(v string) *ConversationEventCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ConversationEventCreate) SetKind(v string) *ConversationEventCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetContentCiphertext sets the "content_ciphertext" field.
func (_c *ConversationEventCreate) SetContentCiphertext(v []byte) *ConversationEventCreate {
	_c.mutation.SetContentCiphertext(v)
	return _c
}

// SetContentNonce sets the "content_nonce" field.
func (_c *ConversationEventCreate) SetContentNonce(v []byte) *ConversationEventCreate {
	_c.mutation.SetContentNonce(v)
	return _c
}

// SetEncryptionKeyVersion sets the "encryption_key_version" field.
func (_c *ConversationEventCreate) SetEncryptionKeyVersion(v int) *ConversationEventCreate {
	_c.mutation.SetEncryptionKeyVersion(v)
	return _c
}

// SetNillableEncryptionKeyVersion sets the "encryption_key_version" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableEncryptionKeyVersion(v *int) *ConversationEventCreate {
	if v != nil {
		_c.SetEncryptionKeyVersion(*v)
	}
	return _c
}

// SetContentPreview sets the "content_preview" field.
func (_c *ConversationEventCreate) SetContentPreview(v string) *ConversationEventCreate {
	_c.mutation.SetContentPreview(v)
	return _c
}

// SetNillableContentPreview sets the "content_preview" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableContentPreview(v *string) *ConversationEventCreate {
	if v != nil {
		_c.SetContentPreview(*v)
	}
	return _c
}

// SetEventHash sets the "event_hash" field.
func (_c *ConversationEventCreate) SetEventHash(v string) *ConversationEventCreate {
	_c.mutation.SetEventHash(v)
	return _c
}

// SetNillableEventHash sets the "event_hash" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableEventHash(v *string) *ConversationEventCreate {
	if v != nil {
		_c.SetEventHash(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ConversationEventCreate) SetModel(v string) *ConversationEventCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableModel(v *string) *ConversationEventCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ConversationEventCreate) SetProvider(v string) *ConversationEventCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableProvider(v *string) *ConversationEventCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetUpstreamResponseIDHash sets the "upstream_response_id_hash" field.
func (_c *ConversationEventCreate) SetUpstreamResponseIDHash(v string) *ConversationEventCreate {
	_c.mutation.SetUpstreamResponseIDHash(v)
	return _c
}

// SetNillableUpstreamResponseIDHash sets the "upstream_response_id_hash" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableUpstreamResponseIDHash(v *string) *ConversationEventCreate {
	if v != nil {
		_c.SetUpstreamResponseIDHash(*v)
	}
	return _c
}

// SetToolCallIDHash sets the "tool_call_id_hash" field.
func (_c *ConversationEventCreate) SetToolCallIDHash(v string) *ConversationEventCreate {
	_c.mutation.SetToolCallIDHash(v)
	return _c
}

// SetNillableToolCallIDHash sets the "tool_call_id_hash" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableToolCallIDHash(v *string) *ConversationEventCreate {
	if v != nil {
		_c.SetToolCallIDHash(*v)
	}
	return _c
}

// SetPartial sets the "partial" field.
func (_c *ConversationEventCreate) SetPartial(v bool) *ConversationEventCreate {
	_c.mutation.SetPartial(v)
	return _c
}

// SetNillablePartial sets the "partial" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillablePartial(v *bool) *ConversationEventCreate {
	if v != nil {
		_c.SetPartial(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationEventCreate) SetCreatedAt(v time.Time) *ConversationEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationEventCreate) SetNillableCreatedAt(v *time.Time) *ConversationEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ConversationEventMutation object of the builder.
func (_c *ConversationEventCreate) Mutation() *ConversationEventMutation {
	return _c.mutation
}

// Save creates the ConversationEvent in the database.
func (_c *ConversationEventCreate) Save(ctx context.Context) (*ConversationEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationEventCreate) SaveX(ctx context.Context) *ConversationEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationEventCreate) defaults() {
	if _, ok := _c.mutation.EncryptionKeyVersion(); !ok {
		v := conversationevent.DefaultEncryptionKeyVersion
		_c.mutation.SetEncryptionKeyVersion(v)
	}
	if _, ok := _c.mutation.Partial(); !ok {
		v := conversationevent.DefaultPartial
		_c.mutation.SetPartial(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversationevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationEventCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ConversationEvent.session_id"`)}
	}
	if _, ok := _c.mutation.BranchID(); !ok {
		return &ValidationError{Name: "branch_id", err: errors.New(`ent: missing required field "ConversationEvent.branch_id"`)}
	}
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "ConversationEvent.sequence"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "ConversationEvent.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := conversationevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ConversationEvent.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := conversationevent.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ConversationEvent.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := conversationevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptionKeyVersion(); !ok {
		return &ValidationError{Name: "encryption_key_version", err: errors.New(`ent: missing required field "ConversationEvent.encryption_key_version"`)}
	}
	if v, ok := _c.mutation.EventHash(); ok {
		if err := conversationevent.EventHashValidator(v); err != nil {
			return &ValidationError{Name: "event_hash", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.event_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := conversationevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := conversationevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamResponseIDHash(); ok {
		if err := conversationevent.UpstreamResponseIDHashValidator(v); err != nil {
			return &ValidationError{Name: "upstream_response_id_hash", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.upstream_response_id_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ToolCallIDHash(); ok {
		if err := conversationevent.ToolCallIDHashValidator(v); err != nil {
			return &ValidationError{Name: "tool_call_id_hash", err: fmt.Errorf(`ent: validator failed for field "ConversationEvent.tool_call_id_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Partial(); !ok {
		return &ValidationError{Name: "partial", err: errors.New(`ent: missing required field "ConversationEvent.partial"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConversationEvent.created_at"`)}
	}
	return nil
}

func (_c *ConversationEventCreate) sqlSave(ctx context.Context) (*ConversationEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationEventCreate) createSpec() (*ConversationEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ConversationEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversationevent.Table, sqlgraph.NewFieldSpec(conversationevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(conversationevent.FieldSessionID, field.TypeUUID, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.BranchID(); ok {
		_spec.SetField(conversationevent.FieldBranchID, field.TypeUUID, value)
		_node.BranchID = value
	}
	if value, ok := _c.mutation.ParentEventID(); ok {
		_spec.SetField(conversationevent.FieldParentEventID, field.TypeInt64, value)
		_node.ParentEventID = &value
	}
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(conversationevent.FieldSequence, field.TypeInt, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(conversationevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(conversationevent.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(conversationevent.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ContentCiphertext(); ok {
		_spec.SetField(conversationevent.FieldContentCiphertext, field.TypeBytes, value)
		_node.ContentCiphertext = &value
	}
	if value, ok := _c.mutation.ContentNonce(); ok {
		_spec.SetField(conversationevent.FieldContentNonce, field.TypeBytes, value)
		_node.ContentNonce = &value
	}
	if value, ok := _c.mutation.EncryptionKeyVersion(); ok {
		_spec.SetField(conversationevent.FieldEncryptionKeyVersion, field.TypeInt, value)
		_node.EncryptionKeyVersion = value
	}
	if value, ok := _c.mutation.ContentPreview(); ok {
		_spec.SetField(conversationevent.FieldContentPreview, field.TypeString, value)
		_node.ContentPreview = value
	}
	if value, ok := _c.mutation.EventHash(); ok {
		_spec.SetField(conversationevent.FieldEventHash, field.TypeString, value)
		_node.EventHash = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(conversationevent.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(conversationevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.UpstreamResponseIDHash(); ok {
		_spec.SetField(conversationevent.FieldUpstreamResponseIDHash, field.TypeString, value)
		_node.UpstreamResponseIDHash = value
	}
	if value, ok := _c.mutation.ToolCallIDHash(); ok {
		_spec.SetField(conversationevent.FieldToolCallIDHash, field.TypeString, value)
		_node.ToolCallIDHash = value
	}
	if value, ok := _c.mutation.Partial(); ok {
		_spec.SetField(conversationevent.FieldPartial, field.TypeBool, value)
		_node.Partial = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversationevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationEvent.Create().
//		SetSessionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationEventUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationEventCreate) OnConflict(opts ...sql.ConflictOption) *ConversationEventUpsertOne {
	_c.conflict = opts
	return &ConversationEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationEventCreate) OnConflictColumns(columns ...string) *ConversationEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationEventUpsertOne{
		create: _c,
	}
}

type (
	// ConversationEventUpsertOne is the builder for "upsert"-ing
	//  one ConversationEvent node.
	ConversationEventUpsertOne struct {
		create *ConversationEventCreate
	}

	// ConversationEventUpsert is the "OnConflict" setter.
	ConversationEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetSessionID sets the "session_id" field.
func (u *ConversationEventUpsert) SetSessionID(v uuid.UUID) *ConversationEventUpsert {
	u.Set(conversationevent.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateSessionID() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldSessionID)
	return u
}

// SetBranchID sets the "branch_id" field.
func (u *ConversationEventUpsert) SetBranchID(v uuid.UUID) *ConversationEventUpsert {
	u.Set(conversationevent.FieldBranchID, v)
	return u
}

// UpdateBranchID sets the "branch_id" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateBranchID() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldBranchID)
	return u
}

// SetParentEventID sets the "parent_event_id" field.
func (u *ConversationEventUpsert) SetParentEventID(v int64) *ConversationEventUpsert {
	u.Set(conversationevent.FieldParentEventID, v)
	return u
}

// UpdateParentEventID sets the "parent_event_id" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateParentEventID() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldParentEventID)
	return u
}

// AddParentEventID adds v to the "parent_event_id" field.
func (u *ConversationEventUpsert) AddParentEventID(v int64) *ConversationEventUpsert {
	u.Add(conversationevent.FieldParentEventID, v)
	return u
}

// ClearParentEventID clears the value of the "parent_event_id" field.
func (u *ConversationEventUpsert) ClearParentEventID() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldParentEventID)
	return u
}

// SetSequence sets the "sequence" field.
func (u *ConversationEventUpsert) SetSequence(v int) *ConversationEventUpsert {
	u.Set(conversationevent.FieldSequence, v)
	return u
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateSequence() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldSequence)
	return u
}

// AddSequence adds v to the "sequence" field.
func (u *ConversationEventUpsert) AddSequence(v int) *ConversationEventUpsert {
	u.Add(conversationevent.FieldSequence, v)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *ConversationEventUpsert) SetRequestID(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateRequestID() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldRequestID)
	return u
}

// SetRole sets the "role" field.
func (u *ConversationEventUpsert) SetRole(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateRole() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldRole)
	return u
}

// SetKind sets the "kind" field.
func (u *ConversationEventUpsert) SetKind(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateKind() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldKind)
	return u
}

// SetContentCiphertext sets the "content_ciphertext" field.
func (u *ConversationEventUpsert) SetContentCiphertext(v []byte) *ConversationEventUpsert {
	u.Set(conversationevent.FieldContentCiphertext, v)
	return u
}

// UpdateContentCiphertext sets the "content_ciphertext" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateContentCiphertext() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldContentCiphertext)
	return u
}

// ClearContentCiphertext clears the value of the "content_ciphertext" field.
func (u *ConversationEventUpsert) ClearContentCiphertext() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldContentCiphertext)
	return u
}

// SetContentNonce sets the "content_nonce" field.
func (u *ConversationEventUpsert) SetContentNonce(v []byte) *ConversationEventUpsert {
	u.Set(conversationevent.FieldContentNonce, v)
	return u
}

// UpdateContentNonce sets the "content_nonce" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateContentNonce() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldContentNonce)
	return u
}

// ClearContentNonce clears the value of the "content_nonce" field.
func (u *ConversationEventUpsert) ClearContentNonce() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldContentNonce)
	return u
}

// SetEncryptionKeyVersion sets the "encryption_key_version" field.
func (u *ConversationEventUpsert) SetEncryptionKeyVersion(v int) *ConversationEventUpsert {
	u.Set(conversationevent.FieldEncryptionKeyVersion, v)
	return u
}

// UpdateEncryptionKeyVersion sets the "encryption_key_version" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateEncryptionKeyVersion() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldEncryptionKeyVersion)
	return u
}

// AddEncryptionKeyVersion adds v to the "encryption_key_version" field.
func (u *ConversationEventUpsert) AddEncryptionKeyVersion(v int) *ConversationEventUpsert {
	u.Add(conversationevent.FieldEncryptionKeyVersion, v)
	return u
}

// SetContentPreview sets the "content_preview" field.
func (u *ConversationEventUpsert) SetContentPreview(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldContentPreview, v)
	return u
}

// UpdateContentPreview sets the "content_preview" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateContentPreview() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldContentPreview)
	return u
}

// ClearContentPreview clears the value of the "content_preview" field.
func (u *ConversationEventUpsert) ClearContentPreview() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldContentPreview)
	return u
}

// SetEventHash sets the "event_hash" field.
func (u *ConversationEventUpsert) SetEventHash(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldEventHash, v)
	return u
}

// UpdateEventHash sets the "event_hash" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateEventHash() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldEventHash)
	return u
}

// ClearEventHash clears the value of the "event_hash" field.
func (u *ConversationEventUpsert) ClearEventHash() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldEventHash)
	return u
}

// SetModel sets the "model" field.
func (u *ConversationEventUpsert) SetModel(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateModel() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *ConversationEventUpsert) ClearModel() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldModel)
	return u
}

// SetProvider sets the "provider" field.
func (u *ConversationEventUpsert) SetProvider(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateProvider() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *ConversationEventUpsert) ClearProvider() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldProvider)
	return u
}

// SetUpstreamResponseIDHash sets the "upstream_response_id_hash" field.
func (u *ConversationEventUpsert) SetUpstreamResponseIDHash(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldUpstreamResponseIDHash, v)
	return u
}

// UpdateUpstreamResponseIDHash sets the "upstream_response_id_hash" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateUpstreamResponseIDHash() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldUpstreamResponseIDHash)
	return u
}

// ClearUpstreamResponseIDHash clears the value of the "upstream_response_id_hash" field.
func (u *ConversationEventUpsert) ClearUpstreamResponseIDHash() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldUpstreamResponseIDHash)
	return u
}

// SetToolCallIDHash sets the "tool_call_id_hash" field.
func (u *ConversationEventUpsert) SetToolCallIDHash(v string) *ConversationEventUpsert {
	u.Set(conversationevent.FieldToolCallIDHash, v)
	return u
}

// UpdateToolCallIDHash sets the "tool_call_id_hash" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdateToolCallIDHash() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldToolCallIDHash)
	return u
}

// ClearToolCallIDHash clears the value of the "tool_call_id_hash" field.
func (u *ConversationEventUpsert) ClearToolCallIDHash() *ConversationEventUpsert {
	u.SetNull(conversationevent.FieldToolCallIDHash)
	return u
}

// SetPartial sets the "partial" field.
func (u *ConversationEventUpsert) SetPartial(v bool) *ConversationEventUpsert {
	u.Set(conversationevent.FieldPartial, v)
	return u
}

// UpdatePartial sets the "partial" field to the value that was provided on create.
func (u *ConversationEventUpsert) UpdatePartial() *ConversationEventUpsert {
	u.SetExcluded(conversationevent.FieldPartial)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ConversationEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationEventUpsertOne) UpdateNewValues() *ConversationEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(conversationevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConversationEventUpsertOne) Ignore() *ConversationEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationEventUpsertOne) DoNothing() *ConversationEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationEventCreate.OnConflict
// documentation for more info.
func (u *ConversationEventUpsertOne) Update(set func(*ConversationEventUpsert)) *ConversationEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *ConversationEventUpsertOne) SetSessionID(v uuid.UUID) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateSessionID() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateSessionID()
	})
}

// SetBranchID sets the "branch_id" field.
func (u *ConversationEventUpsertOne) SetBranchID(v uuid.UUID) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetBranchID(v)
	})
}

// UpdateBranchID sets the "branch_id" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateBranchID() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateBranchID()
	})
}

// SetParentEventID sets the "parent_event_id" field.
func (u *ConversationEventUpsertOne) SetParentEventID(v int64) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetParentEventID(v)
	})
}

// AddParentEventID adds v to the "parent_event_id" field.
func (u *ConversationEventUpsertOne) AddParentEventID(v int64) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.AddParentEventID(v)
	})
}

// UpdateParentEventID sets the "parent_event_id" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateParentEventID() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateParentEventID()
	})
}

// ClearParentEventID clears the value of the "parent_event_id" field.
func (u *ConversationEventUpsertOne) ClearParentEventID() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearParentEventID()
	})
}

// SetSequence sets the "sequence" field.
func (u *ConversationEventUpsertOne) SetSequence(v int) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetSequence(v)
	})
}

// AddSequence adds v to the "sequence" field.
func (u *ConversationEventUpsertOne) AddSequence(v int) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.AddSequence(v)
	})
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateSequence() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateSequence()
	})
}

// SetRequestID sets the "request_id" field.
func (u *ConversationEventUpsertOne) SetRequestID(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateRequestID() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateRequestID()
	})
}

// SetRole sets the "role" field.
func (u *ConversationEventUpsertOne) SetRole(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateRole() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateRole()
	})
}

// SetKind sets the "kind" field.
func (u *ConversationEventUpsertOne) SetKind(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateKind() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateKind()
	})
}

// SetContentCiphertext sets the "content_ciphertext" field.
func (u *ConversationEventUpsertOne) SetContentCiphertext(v []byte) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetContentCiphertext(v)
	})
}

// UpdateContentCiphertext sets the "content_ciphertext" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateContentCiphertext() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateContentCiphertext()
	})
}

// ClearContentCiphertext clears the value of the "content_ciphertext" field.
func (u *ConversationEventUpsertOne) ClearContentCiphertext() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearContentCiphertext()
	})
}

// SetContentNonce sets the "content_nonce" field.
func (u *ConversationEventUpsertOne) SetContentNonce(v []byte) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetContentNonce(v)
	})
}

// UpdateContentNonce sets the "content_nonce" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateContentNonce() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateContentNonce()
	})
}

// ClearContentNonce clears the value of the "content_nonce" field.
func (u *ConversationEventUpsertOne) ClearContentNonce() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearContentNonce()
	})
}

// SetEncryptionKeyVersion sets the "encryption_key_version" field.
func (u *ConversationEventUpsertOne) SetEncryptionKeyVersion(v int) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetEncryptionKeyVersion(v)
	})
}

// AddEncryptionKeyVersion adds v to the "encryption_key_version" field.
func (u *ConversationEventUpsertOne) AddEncryptionKeyVersion(v int) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.AddEncryptionKeyVersion(v)
	})
}

// UpdateEncryptionKeyVersion sets the "encryption_key_version" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateEncryptionKeyVersion() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateEncryptionKeyVersion()
	})
}

// SetContentPreview sets the "content_preview" field.
func (u *ConversationEventUpsertOne) SetContentPreview(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetContentPreview(v)
	})
}

// UpdateContentPreview sets the "content_preview" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateContentPreview() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateContentPreview()
	})
}

// ClearContentPreview clears the value of the "content_preview" field.
func (u *ConversationEventUpsertOne) ClearContentPreview() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearContentPreview()
	})
}

// SetEventHash sets the "event_hash" field.
func (u *ConversationEventUpsertOne) SetEventHash(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetEventHash(v)
	})
}

// UpdateEventHash sets the "event_hash" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateEventHash() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateEventHash()
	})
}

// ClearEventHash clears the value of the "event_hash" field.
func (u *ConversationEventUpsertOne) ClearEventHash() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearEventHash()
	})
}

// SetModel sets the "model" field.
func (u *ConversationEventUpsertOne) SetModel(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateModel() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *ConversationEventUpsertOne) ClearModel() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearModel()
	})
}

// SetProvider sets the "provider" field.
func (u *ConversationEventUpsertOne) SetProvider(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateProvider() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *ConversationEventUpsertOne) ClearProvider() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearProvider()
	})
}

// SetUpstreamResponseIDHash sets the "upstream_response_id_hash" field.
func (u *ConversationEventUpsertOne) SetUpstreamResponseIDHash(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetUpstreamResponseIDHash(v)
	})
}

// UpdateUpstreamResponseIDHash sets the "upstream_response_id_hash" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateUpstreamResponseIDHash() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateUpstreamResponseIDHash()
	})
}

// ClearUpstreamResponseIDHash clears the value of the "upstream_response_id_hash" field.
func (u *ConversationEventUpsertOne) ClearUpstreamResponseIDHash() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearUpstreamResponseIDHash()
	})
}

// SetToolCallIDHash sets the "tool_call_id_hash" field.
func (u *ConversationEventUpsertOne) SetToolCallIDHash(v string) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetToolCallIDHash(v)
	})
}

// UpdateToolCallIDHash sets the "tool_call_id_hash" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdateToolCallIDHash() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateToolCallIDHash()
	})
}

// ClearToolCallIDHash clears the value of the "tool_call_id_hash" field.
func (u *ConversationEventUpsertOne) ClearToolCallIDHash() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearToolCallIDHash()
	})
}

// SetPartial sets the "partial" field.
func (u *ConversationEventUpsertOne) SetPartial(v bool) *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetPartial(v)
	})
}

// UpdatePartial sets the "partial" field to the value that was provided on create.
func (u *ConversationEventUpsertOne) UpdatePartial() *ConversationEventUpsertOne {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdatePartial()
	})
}

// Exec executes the query.
func (u *ConversationEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConversationEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConversationEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConversationEventCreateBulk is the builder for creating many ConversationEvent entities in bulk.
type ConversationEventCreateBulk struct {
	config
	err      error
	builders []*ConversationEventCreate
	conflict []sql.ConflictOption
}

// Save creates the ConversationEvent entities in the database.
func (_c *ConversationEventCreateBulk) Save(ctx context.Context) ([]*ConversationEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConversationEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationEventCreateBulk) SaveX(ctx context.Context) []*ConversationEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationEventUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConversationEventUpsertBulk {
	_c.conflict = opts
	return &ConversationEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationEventCreateBulk) OnConflictColumns(columns ...string) *ConversationEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationEventUpsertBulk{
		create: _c,
	}
}

// ConversationEventUpsertBulk is the builder for "upsert"-ing
// a bulk of ConversationEvent nodes.
type ConversationEventUpsertBulk struct {
	create *ConversationEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ConversationEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationEventUpsertBulk) UpdateNewValues() *ConversationEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(conversationevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConversationEventUpsertBulk) Ignore() *ConversationEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationEventUpsertBulk) DoNothing() *ConversationEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationEventCreateBulk.OnConflict
// documentation for more info.
func (u *ConversationEventUpsertBulk) Update(set func(*ConversationEventUpsert)) *ConversationEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *ConversationEventUpsertBulk) SetSessionID(v uuid.UUID) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateSessionID() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateSessionID()
	})
}

// SetBranchID sets the "branch_id" field.
func (u *ConversationEventUpsertBulk) SetBranchID(v uuid.UUID) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetBranchID(v)
	})
}

// UpdateBranchID sets the "branch_id" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateBranchID() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateBranchID()
	})
}

// SetParentEventID sets the "parent_event_id" field.
func (u *ConversationEventUpsertBulk) SetParentEventID(v int64) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetParentEventID(v)
	})
}

// AddParentEventID adds v to the "parent_event_id" field.
func (u *ConversationEventUpsertBulk) AddParentEventID(v int64) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.AddParentEventID(v)
	})
}

// UpdateParentEventID sets the "parent_event_id" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateParentEventID() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateParentEventID()
	})
}

// ClearParentEventID clears the value of the "parent_event_id" field.
func (u *ConversationEventUpsertBulk) ClearParentEventID() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearParentEventID()
	})
}

// SetSequence sets the "sequence" field.
func (u *ConversationEventUpsertBulk) SetSequence(v int) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetSequence(v)
	})
}

// AddSequence adds v to the "sequence" field.
func (u *ConversationEventUpsertBulk) AddSequence(v int) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.AddSequence(v)
	})
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateSequence() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateSequence()
	})
}

// SetRequestID sets the "request_id" field.
func (u *ConversationEventUpsertBulk) SetRequestID(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateRequestID() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateRequestID()
	})
}

// SetRole sets the "role" field.
func (u *ConversationEventUpsertBulk) SetRole(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateRole() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateRole()
	})
}

// SetKind sets the "kind" field.
func (u *ConversationEventUpsertBulk) SetKind(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateKind() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateKind()
	})
}

// SetContentCiphertext sets the "content_ciphertext" field.
func (u *ConversationEventUpsertBulk) SetContentCiphertext(v []byte) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetContentCiphertext(v)
	})
}

// UpdateContentCiphertext sets the "content_ciphertext" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateContentCiphertext() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateContentCiphertext()
	})
}

// ClearContentCiphertext clears the value of the "content_ciphertext" field.
func (u *ConversationEventUpsertBulk) ClearContentCiphertext() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearContentCiphertext()
	})
}

// SetContentNonce sets the "content_nonce" field.
func (u *ConversationEventUpsertBulk) SetContentNonce(v []byte) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetContentNonce(v)
	})
}

// UpdateContentNonce sets the "content_nonce" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateContentNonce() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateContentNonce()
	})
}

// ClearContentNonce clears the value of the "content_nonce" field.
func (u *ConversationEventUpsertBulk) ClearContentNonce() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearContentNonce()
	})
}

// SetEncryptionKeyVersion sets the "encryption_key_version" field.
func (u *ConversationEventUpsertBulk) SetEncryptionKeyVersion(v int) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetEncryptionKeyVersion(v)
	})
}

// AddEncryptionKeyVersion adds v to the "encryption_key_version" field.
func (u *ConversationEventUpsertBulk) AddEncryptionKeyVersion(v int) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.AddEncryptionKeyVersion(v)
	})
}

// UpdateEncryptionKeyVersion sets the "encryption_key_version" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateEncryptionKeyVersion() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateEncryptionKeyVersion()
	})
}

// SetContentPreview sets the "content_preview" field.
func (u *ConversationEventUpsertBulk) SetContentPreview(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetContentPreview(v)
	})
}

// UpdateContentPreview sets the "content_preview" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateContentPreview() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateContentPreview()
	})
}

// ClearContentPreview clears the value of the "content_preview" field.
func (u *ConversationEventUpsertBulk) ClearContentPreview() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearContentPreview()
	})
}

// SetEventHash sets the "event_hash" field.
func (u *ConversationEventUpsertBulk) SetEventHash(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetEventHash(v)
	})
}

// UpdateEventHash sets the "event_hash" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateEventHash() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateEventHash()
	})
}

// ClearEventHash clears the value of the "event_hash" field.
func (u *ConversationEventUpsertBulk) ClearEventHash() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearEventHash()
	})
}

// SetModel sets the "model" field.
func (u *ConversationEventUpsertBulk) SetModel(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateModel() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *ConversationEventUpsertBulk) ClearModel() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearModel()
	})
}

// SetProvider sets the "provider" field.
func (u *ConversationEventUpsertBulk) SetProvider(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateProvider() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *ConversationEventUpsertBulk) ClearProvider() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearProvider()
	})
}

// SetUpstreamResponseIDHash sets the "upstream_response_id_hash" field.
func (u *ConversationEventUpsertBulk) SetUpstreamResponseIDHash(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetUpstreamResponseIDHash(v)
	})
}

// UpdateUpstreamResponseIDHash sets the "upstream_response_id_hash" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateUpstreamResponseIDHash() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateUpstreamResponseIDHash()
	})
}

// ClearUpstreamResponseIDHash clears the value of the "upstream_response_id_hash" field.
func (u *ConversationEventUpsertBulk) ClearUpstreamResponseIDHash() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearUpstreamResponseIDHash()
	})
}

// SetToolCallIDHash sets the "tool_call_id_hash" field.
func (u *ConversationEventUpsertBulk) SetToolCallIDHash(v string) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetToolCallIDHash(v)
	})
}

// UpdateToolCallIDHash sets the "tool_call_id_hash" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdateToolCallIDHash() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdateToolCallIDHash()
	})
}

// ClearToolCallIDHash clears the value of the "tool_call_id_hash" field.
func (u *ConversationEventUpsertBulk) ClearToolCallIDHash() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.ClearToolCallIDHash()
	})
}

// SetPartial sets the "partial" field.
func (u *ConversationEventUpsertBulk) SetPartial(v bool) *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.SetPartial(v)
	})
}

// UpdatePartial sets the "partial" field to the value that was provided on create.
func (u *ConversationEventUpsertBulk) UpdatePartial() *ConversationEventUpsertBulk {
	return u.Update(func(s *ConversationEventUpsert) {
		s.UpdatePartial()
	})
}

// Exec executes the query.
func (u *ConversationEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConversationEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
