// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/researchgroup"
	"github.com/Wei-Shaw/sub2api/ent/researchgroupmember"
	"github.com/Wei-Shaw/sub2api/ent/researchgroupquotaaudit"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResearchGroupUpdate is the builder for updating ResearchGroup entities.
type ResearchGroupUpdate struct {
	config
	hooks    []Hook
	mutation *ResearchGroupMutation
}

// Where appends a list predicates to the ResearchGroupUpdate builder.
func (_u *ResearchGroupUpdate) Where(ps ...predicate.ResearchGroup) *ResearchGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ResearchGroupUpdate) SetName(v string) *ResearchGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResearchGroupUpdate) SetNillableName(v *string) *ResearchGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ResearchGroupUpdate) SetOwnerUserID(v int64) *ResearchGroupUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ResearchGroupUpdate) SetNillableOwnerUserID(v *int64) *ResearchGroupUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *ResearchGroupUpdate) ClearOwnerUserID() *ResearchGroupUpdate {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResearchGroupUpdate) SetStatus(v string) *ResearchGroupUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResearchGroupUpdate) SetNillableStatus(v *string) *ResearchGroupUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResearchGroupUpdate) SetUpdatedAt(v time.Time) *ResearchGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDissolvedAt sets the "dissolved_at" field.
func (_u *ResearchGroupUpdate) SetDissolvedAt(v time.Time) *ResearchGroupUpdate {
	_u.mutation.SetDissolvedAt(v)
	return _u
}

// SetNillableDissolvedAt sets the "dissolved_at" field if the given value is not nil.
func (_u *ResearchGroupUpdate) SetNillableDissolvedAt(v *time.Time) *ResearchGroupUpdate {
	if v != nil {
		_u.SetDissolvedAt(*v)
	}
	return _u
}

// ClearDissolvedAt clears the value of the "dissolved_at" field.
func (_u *ResearchGroupUpdate) ClearDissolvedAt() *ResearchGroupUpdate {
	_u.mutation.ClearDissolvedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ResearchGroupUpdate) SetOwnerID(id int64) *ResearchGroupUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ResearchGroupUpdate) SetNillableOwnerID(id *int64) *ResearchGroupUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ResearchGroupUpdate) SetOwner(v *User) *ResearchGroupUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the ResearchGroupMember entity by IDs.
func (_u *ResearchGroupUpdate) AddMemberIDs(ids ...int64) *ResearchGroupUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the ResearchGroupMember entity.
func (_u *ResearchGroupUpdate) AddMembers(v ...*ResearchGroupMember) *ResearchGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddQuotaAuditIDs adds the "quota_audits" edge to the ResearchGroupQuotaAudit entity by IDs.
func (_u *ResearchGroupUpdate) AddQuotaAuditIDs(ids ...int64) *ResearchGroupUpdate {
	_u.mutation.AddQuotaAuditIDs(ids...)
	return _u
}

// AddQuotaAudits adds the "quota_audits" edges to the ResearchGroupQuotaAudit entity.
func (_u *ResearchGroupUpdate) AddQuotaAudits(v ...*ResearchGroupQuotaAudit) *ResearchGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuotaAuditIDs(ids...)
}

// AddFundedUsageLogIDs adds the "funded_usage_logs" edge to the UsageLog entity by IDs.
func (_u *ResearchGroupUpdate) AddFundedUsageLogIDs(ids ...int64) *ResearchGroupUpdate {
	_u.mutation.AddFundedUsageLogIDs(ids...)
	return _u
}

// AddFundedUsageLogs adds the "funded_usage_logs" edges to the UsageLog entity.
func (_u *ResearchGroupUpdate) AddFundedUsageLogs(v ...*UsageLog) *ResearchGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFundedUsageLogIDs(ids...)
}

// Mutation returns the ResearchGroupMutation object of the builder.
func (_u *ResearchGroupUpdate) Mutation() *ResearchGroupMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ResearchGroupUpdate) ClearOwner() *ResearchGroupUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMembers clears all "members" edges to the ResearchGroupMember entity.
func (_u *ResearchGroupUpdate) ClearMembers() *ResearchGroupUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to ResearchGroupMember entities by IDs.
func (_u *ResearchGroupUpdate) RemoveMemberIDs(ids ...int64) *ResearchGroupUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to ResearchGroupMember entities.
func (_u *ResearchGroupUpdate) RemoveMembers(v ...*ResearchGroupMember) *ResearchGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearQuotaAudits clears all "quota_audits" edges to the ResearchGroupQuotaAudit entity.
func (_u *ResearchGroupUpdate) ClearQuotaAudits() *ResearchGroupUpdate {
	_u.mutation.ClearQuotaAudits()
	return _u
}

// RemoveQuotaAuditIDs removes the "quota_audits" edge to ResearchGroupQuotaAudit entities by IDs.
func (_u *ResearchGroupUpdate) RemoveQuotaAuditIDs(ids ...int64) *ResearchGroupUpdate {
	_u.mutation.RemoveQuotaAuditIDs(ids...)
	return _u
}

// RemoveQuotaAudits removes "quota_audits" edges to ResearchGroupQuotaAudit entities.
func (_u *ResearchGroupUpdate) RemoveQuotaAudits(v ...*ResearchGroupQuotaAudit) *ResearchGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuotaAuditIDs(ids...)
}

// ClearFundedUsageLogs clears all "funded_usage_logs" edges to the UsageLog entity.
func (_u *ResearchGroupUpdate) ClearFundedUsageLogs() *ResearchGroupUpdate {
	_u.mutation.ClearFundedUsageLogs()
	return _u
}

// RemoveFundedUsageLogIDs removes the "funded_usage_logs" edge to UsageLog entities by IDs.
func (_u *ResearchGroupUpdate) RemoveFundedUsageLogIDs(ids ...int64) *ResearchGroupUpdate {
	_u.mutation.RemoveFundedUsageLogIDs(ids...)
	return _u
}

// RemoveFundedUsageLogs removes "funded_usage_logs" edges to UsageLog entities.
func (_u *ResearchGroupUpdate) RemoveFundedUsageLogs(v ...*UsageLog) *ResearchGroupUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFundedUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResearchGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResearchGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResearchGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResearchGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResearchGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := researchgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResearchGroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := researchgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResearchGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := researchgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResearchGroup.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResearchGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(researchgroup.Table, researchgroup.Columns, sqlgraph.NewFieldSpec(researchgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(researchgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(researchgroup.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(researchgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DissolvedAt(); ok {
		_spec.SetField(researchgroup.FieldDissolvedAt, field.TypeTime, value)
	}
	if _u.mutation.DissolvedAtCleared() {
		_spec.ClearField(researchgroup.FieldDissolvedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   researchgroup.OwnerTable,
			Columns: []string{researchgroup.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   researchgroup.OwnerTable,
			Columns: []string{researchgroup.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.MembersTable,
			Columns: []string{researchgroup.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.MembersTable,
			Columns: []string{researchgroup.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.MembersTable,
			Columns: []string{researchgroup.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuotaAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.QuotaAuditsTable,
			Columns: []string{researchgroup.QuotaAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupquotaaudit.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuotaAuditsIDs(); len(nodes) > 0 && !_u.mutation.QuotaAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.QuotaAuditsTable,
			Columns: []string{researchgroup.QuotaAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupquotaaudit.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuotaAuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.QuotaAuditsTable,
			Columns: []string{researchgroup.QuotaAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupquotaaudit.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FundedUsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.FundedUsageLogsTable,
			Columns: []string{researchgroup.FundedUsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFundedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.FundedUsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.FundedUsageLogsTable,
			Columns: []string{researchgroup.FundedUsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FundedUsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.FundedUsageLogsTable,
			Columns: []string{researchgroup.FundedUsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{researchgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResearchGroupUpdateOne is the builder for updating a single ResearchGroup entity.
type ResearchGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResearchGroupMutation
}

// SetName sets the "name" field.
func (_u *ResearchGroupUpdateOne) SetName(v string) *ResearchGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResearchGroupUpdateOne) SetNillableName(v *string) *ResearchGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ResearchGroupUpdateOne) SetOwnerUserID(v int64) *ResearchGroupUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ResearchGroupUpdateOne) SetNillableOwnerUserID(v *int64) *ResearchGroupUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (_u *ResearchGroupUpdateOne) ClearOwnerUserID() *ResearchGroupUpdateOne {
	_u.mutation.ClearOwnerUserID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResearchGroupUpdateOne) SetStatus(v string) *ResearchGroupUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResearchGroupUpdateOne) SetNillableStatus(v *string) *ResearchGroupUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResearchGroupUpdateOne) SetUpdatedAt(v time.Time) *ResearchGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDissolvedAt sets the "dissolved_at" field.
func (_u *ResearchGroupUpdateOne) SetDissolvedAt(v time.Time) *ResearchGroupUpdateOne {
	_u.mutation.SetDissolvedAt(v)
	return _u
}

// SetNillableDissolvedAt sets the "dissolved_at" field if the given value is not nil.
func (_u *ResearchGroupUpdateOne) SetNillableDissolvedAt(v *time.Time) *ResearchGroupUpdateOne {
	if v != nil {
		_u.SetDissolvedAt(*v)
	}
	return _u
}

// ClearDissolvedAt clears the value of the "dissolved_at" field.
func (_u *ResearchGroupUpdateOne) ClearDissolvedAt() *ResearchGroupUpdateOne {
	_u.mutation.ClearDissolvedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ResearchGroupUpdateOne) SetOwnerID(id int64) *ResearchGroupUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ResearchGroupUpdateOne) SetNillableOwnerID(id *int64) *ResearchGroupUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ResearchGroupUpdateOne) SetOwner(v *User) *ResearchGroupUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the ResearchGroupMember entity by IDs.
func (_u *ResearchGroupUpdateOne) AddMemberIDs(ids ...int64) *ResearchGroupUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the ResearchGroupMember entity.
func (_u *ResearchGroupUpdateOne) AddMembers(v ...*ResearchGroupMember) *ResearchGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddQuotaAuditIDs adds the "quota_audits" edge to the ResearchGroupQuotaAudit entity by IDs.
func (_u *ResearchGroupUpdateOne) AddQuotaAuditIDs(ids ...int64) *ResearchGroupUpdateOne {
	_u.mutation.AddQuotaAuditIDs(ids...)
	return _u
}

// AddQuotaAudits adds the "quota_audits" edges to the ResearchGroupQuotaAudit entity.
func (_u *ResearchGroupUpdateOne) AddQuotaAudits(v ...*ResearchGroupQuotaAudit) *ResearchGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuotaAuditIDs(ids...)
}

// AddFundedUsageLogIDs adds the "funded_usage_logs" edge to the UsageLog entity by IDs.
func (_u *ResearchGroupUpdateOne) AddFundedUsageLogIDs(ids ...int64) *ResearchGroupUpdateOne {
	_u.mutation.AddFundedUsageLogIDs(ids...)
	return _u
}

// AddFundedUsageLogs adds the "funded_usage_logs" edges to the UsageLog entity.
func (_u *ResearchGroupUpdateOne) AddFundedUsageLogs(v ...*UsageLog) *ResearchGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFundedUsageLogIDs(ids...)
}

// Mutation returns the ResearchGroupMutation object of the builder.
func (_u *ResearchGroupUpdateOne) Mutation() *ResearchGroupMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ResearchGroupUpdateOne) ClearOwner() *ResearchGroupUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMembers clears all "members" edges to the ResearchGroupMember entity.
func (_u *ResearchGroupUpdateOne) ClearMembers() *ResearchGroupUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to ResearchGroupMember entities by IDs.
func (_u *ResearchGroupUpdateOne) RemoveMemberIDs(ids ...int64) *ResearchGroupUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to ResearchGroupMember entities.
func (_u *ResearchGroupUpdateOne) RemoveMembers(v ...*ResearchGroupMember) *ResearchGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearQuotaAudits clears all "quota_audits" edges to the ResearchGroupQuotaAudit entity.
func (_u *ResearchGroupUpdateOne) ClearQuotaAudits() *ResearchGroupUpdateOne {
	_u.mutation.ClearQuotaAudits()
	return _u
}

// RemoveQuotaAuditIDs removes the "quota_audits" edge to ResearchGroupQuotaAudit entities by IDs.
func (_u *ResearchGroupUpdateOne) RemoveQuotaAuditIDs(ids ...int64) *ResearchGroupUpdateOne {
	_u.mutation.RemoveQuotaAuditIDs(ids...)
	return _u
}

// RemoveQuotaAudits removes "quota_audits" edges to ResearchGroupQuotaAudit entities.
func (_u *ResearchGroupUpdateOne) RemoveQuotaAudits(v ...*ResearchGroupQuotaAudit) *ResearchGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuotaAuditIDs(ids...)
}

// ClearFundedUsageLogs clears all "funded_usage_logs" edges to the UsageLog entity.
func (_u *ResearchGroupUpdateOne) ClearFundedUsageLogs() *ResearchGroupUpdateOne {
	_u.mutation.ClearFundedUsageLogs()
	return _u
}

// RemoveFundedUsageLogIDs removes the "funded_usage_logs" edge to UsageLog entities by IDs.
func (_u *ResearchGroupUpdateOne) RemoveFundedUsageLogIDs(ids ...int64) *ResearchGroupUpdateOne {
	_u.mutation.RemoveFundedUsageLogIDs(ids...)
	return _u
}

// RemoveFundedUsageLogs removes "funded_usage_logs" edges to UsageLog entities.
func (_u *ResearchGroupUpdateOne) RemoveFundedUsageLogs(v ...*UsageLog) *ResearchGroupUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFundedUsageLogIDs(ids...)
}

// Where appends a list predicates to the ResearchGroupUpdate builder.
func (_u *ResearchGroupUpdateOne) Where(ps ...predicate.ResearchGroup) *ResearchGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResearchGroupUpdateOne) Select(field string, fields ...string) *ResearchGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResearchGroup entity.
func (_u *ResearchGroupUpdateOne) Save(ctx context.Context) (*ResearchGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResearchGroupUpdateOne) SaveX(ctx context.Context) *ResearchGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResearchGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResearchGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResearchGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := researchgroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResearchGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := researchgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ResearchGroup.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := researchgroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResearchGroup.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResearchGroupUpdateOne) sqlSave(ctx context.Context) (_node *ResearchGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(researchgroup.Table, researchgroup.Columns, sqlgraph.NewFieldSpec(researchgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResearchGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, researchgroup.FieldID)
		for _, f := range fields {
			if !researchgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != researchgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(researchgroup.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(researchgroup.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(researchgroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DissolvedAt(); ok {
		_spec.SetField(researchgroup.FieldDissolvedAt, field.TypeTime, value)
	}
	if _u.mutation.DissolvedAtCleared() {
		_spec.ClearField(researchgroup.FieldDissolvedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   researchgroup.OwnerTable,
			Columns: []string{researchgroup.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   researchgroup.OwnerTable,
			Columns: []string{researchgroup.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.MembersTable,
			Columns: []string{researchgroup.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupmember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.MembersTable,
			Columns: []string{researchgroup.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.MembersTable,
			Columns: []string{researchgroup.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuotaAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.QuotaAuditsTable,
			Columns: []string{researchgroup.QuotaAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupquotaaudit.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuotaAuditsIDs(); len(nodes) > 0 && !_u.mutation.QuotaAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.QuotaAuditsTable,
			Columns: []string{researchgroup.QuotaAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupquotaaudit.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuotaAuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.QuotaAuditsTable,
			Columns: []string{researchgroup.QuotaAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroupquotaaudit.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FundedUsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.FundedUsageLogsTable,
			Columns: []string{researchgroup.FundedUsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFundedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.FundedUsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.FundedUsageLogsTable,
			Columns: []string{researchgroup.FundedUsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FundedUsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   researchgroup.FundedUsageLogsTable,
			Columns: []string{researchgroup.FundedUsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ResearchGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{researchgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
