// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/researchgroup"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResearchGroup is the model entity for the ResearchGroup schema.
type ResearchGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID *int64 `json:"owner_user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DissolvedAt holds the value of the "dissolved_at" field.
	DissolvedAt *time.Time `json:"dissolved_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResearchGroupQuery when eager-loading is set.
	Edges        ResearchGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResearchGroupEdges holds the relations/edges for other nodes in the graph.
type ResearchGroupEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Members holds the value of the members edge.
	Members []*ResearchGroupMember `json:"members,omitempty"`
	// QuotaAudits holds the value of the quota_audits edge.
	QuotaAudits []*ResearchGroupQuotaAudit `json:"quota_audits,omitempty"`
	// FundedUsageLogs holds the value of the funded_usage_logs edge.
	FundedUsageLogs []*UsageLog `json:"funded_usage_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResearchGroupEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e ResearchGroupEdges) MembersOrErr() ([]*ResearchGroupMember, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// QuotaAuditsOrErr returns the QuotaAudits value or an error if the edge
// was not loaded in eager-loading.
func (e ResearchGroupEdges) QuotaAuditsOrErr() ([]*ResearchGroupQuotaAudit, error) {
	if e.loadedTypes[2] {
		return e.QuotaAudits, nil
	}
	return nil, &NotLoadedError{edge: "quota_audits"}
}

// FundedUsageLogsOrErr returns the FundedUsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e ResearchGroupEdges) FundedUsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[3] {
		return e.FundedUsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "funded_usage_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResearchGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case researchgroup.FieldID, researchgroup.FieldOwnerUserID:
			values[i] = new(sql.NullInt64)
		case researchgroup.FieldName, researchgroup.FieldStatus:
			values[i] = new(sql.NullString)
		case researchgroup.FieldCreatedAt, researchgroup.FieldUpdatedAt, researchgroup.FieldDissolvedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResearchGroup fields.
func (_m *ResearchGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case researchgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case researchgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case researchgroup.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = new(int64)
				*_m.OwnerUserID = value.Int64
			}
		case researchgroup.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case researchgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case researchgroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case researchgroup.FieldDissolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dissolved_at", values[i])
			} else if value.Valid {
				_m.DissolvedAt = new(time.Time)
				*_m.DissolvedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResearchGroup.
// This includes values selected through modifiers, order, etc.
func (_m *ResearchGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the ResearchGroup entity.
func (_m *ResearchGroup) QueryOwner() *UserQuery {
	return NewResearchGroupClient(_m.config).QueryOwner(_m)
}

// QueryMembers queries the "members" edge of the ResearchGroup entity.
func (_m *ResearchGroup) QueryMembers() *ResearchGroupMemberQuery {
	return NewResearchGroupClient(_m.config).QueryMembers(_m)
}

// QueryQuotaAudits queries the "quota_audits" edge of the ResearchGroup entity.
func (_m *ResearchGroup) QueryQuotaAudits() *ResearchGroupQuotaAuditQuery {
	return NewResearchGroupClient(_m.config).QueryQuotaAudits(_m)
}

// QueryFundedUsageLogs queries the "funded_usage_logs" edge of the ResearchGroup entity.
func (_m *ResearchGroup) QueryFundedUsageLogs() *UsageLogQuery {
	return NewResearchGroupClient(_m.config).QueryFundedUsageLogs(_m)
}

// Update returns a builder for updating this ResearchGroup.
// Note that you need to call ResearchGroup.Unwrap() before calling this method if this ResearchGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResearchGroup) Update() *ResearchGroupUpdateOne {
	return NewResearchGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResearchGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResearchGroup) Unwrap() *ResearchGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResearchGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResearchGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ResearchGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.OwnerUserID; v != nil {
		builder.WriteString("owner_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DissolvedAt; v != nil {
		builder.WriteString("dissolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ResearchGroups is a parsable slice of ResearchGroup.
type ResearchGroups []*ResearchGroup
