// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/researchgroup"
	"github.com/Wei-Shaw/sub2api/ent/researchgroupquotaaudit"
)

// ResearchGroupQuotaAuditCreate is the builder for creating a ResearchGroupQuotaAudit entity.
type ResearchGroupQuotaAuditCreate struct {
	config
	mutation *ResearchGroupQuotaAuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResearchGroupID sets the "research_group_id" field.
func (_c *ResearchGroupQuotaAuditCreate) SetResearchGroupID(v int64) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetResearchGroupID(v)
	return _c
}

// SetMemberID sets the "member_id" field.
func (_c *ResearchGroupQuotaAuditCreate) SetMemberID(v int64) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_c *ResearchGroupQuotaAuditCreate) SetNillableMemberID(v *int64) *ResearchGroupQuotaAuditCreate {
	if v != nil {
		_c.SetMemberID(*v)
	}
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *ResearchGroupQuotaAuditCreate) SetActorUserID(v int64) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_c *ResearchGroupQuotaAuditCreate) SetNillableActorUserID(v *int64) *ResearchGroupQuotaAuditCreate {
	if v != nil {
		_c.SetActorUserID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *ResearchGroupQuotaAuditCreate) SetAction(v string) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetAmountUsd sets the "amount_usd" field.
func (_c *ResearchGroupQuotaAuditCreate) SetAmountUsd(v float64) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetAmountUsd(v)
	return _c
}

// SetNillableAmountUsd sets the "amount_usd" field if the given value is not nil.
func (_c *ResearchGroupQuotaAuditCreate) SetNillableAmountUsd(v *float64) *ResearchGroupQuotaAuditCreate {
	if v != nil {
		_c.SetAmountUsd(*v)
	}
	return _c
}

// SetPreviousValueUsd sets the "previous_value_usd" field.
func (_c *ResearchGroupQuotaAuditCreate) SetPreviousValueUsd(v float64) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetPreviousValueUsd(v)
	return _c
}

// SetNillablePreviousValueUsd sets the "previous_value_usd" field if the given value is not nil.
func (_c *ResearchGroupQuotaAuditCreate) SetNillablePreviousValueUsd(v *float64) *ResearchGroupQuotaAuditCreate {
	if v != nil {
		_c.SetPreviousValueUsd(*v)
	}
	return _c
}

// SetNewValueUsd sets the "new_value_usd" field.
func (_c *ResearchGroupQuotaAuditCreate) SetNewValueUsd(v float64) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetNewValueUsd(v)
	return _c
}

// SetNillableNewValueUsd sets the "new_value_usd" field if the given value is not nil.
func (_c *ResearchGroupQuotaAuditCreate) SetNillableNewValueUsd(v *float64) *ResearchGroupQuotaAuditCreate {
	if v != nil {
		_c.SetNewValueUsd(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ResearchGroupQuotaAuditCreate) SetMetadata(v map[string]interface{}) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResearchGroupQuotaAuditCreate) SetCreatedAt(v time.Time) *ResearchGroupQuotaAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResearchGroupQuotaAuditCreate) SetNillableCreatedAt(v *time.Time) *ResearchGroupQuotaAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetResearchGroup sets the "research_group" edge to the ResearchGroup entity.
func (_c *ResearchGroupQuotaAuditCreate) SetResearchGroup(v *ResearchGroup) *ResearchGroupQuotaAuditCreate {
	return _c.SetResearchGroupID(v.ID)
}

// Mutation returns the ResearchGroupQuotaAuditMutation object of the builder.
func (_c *ResearchGroupQuotaAuditCreate) Mutation() *ResearchGroupQuotaAuditMutation {
	return _c.mutation
}

// Save creates the ResearchGroupQuotaAudit in the database.
func (_c *ResearchGroupQuotaAuditCreate) Save(ctx context.Context) (*ResearchGroupQuotaAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResearchGroupQuotaAuditCreate) SaveX(ctx context.Context) *ResearchGroupQuotaAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResearchGroupQuotaAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResearchGroupQuotaAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResearchGroupQuotaAuditCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := researchgroupquotaaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResearchGroupQuotaAuditCreate) check() error {
	if _, ok := _c.mutation.ResearchGroupID(); !ok {
		return &ValidationError{Name: "research_group_id", err: errors.New(`ent: missing required field "ResearchGroupQuotaAudit.research_group_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "ResearchGroupQuotaAudit.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := researchgroupquotaaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ResearchGroupQuotaAudit.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResearchGroupQuotaAudit.created_at"`)}
	}
	if len(_c.mutation.ResearchGroupIDs()) == 0 {
		return &ValidationError{Name: "research_group", err: errors.New(`ent: missing required edge "ResearchGroupQuotaAudit.research_group"`)}
	}
	return nil
}

func (_c *ResearchGroupQuotaAuditCreate) sqlSave(ctx context.Context) (*ResearchGroupQuotaAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResearchGroupQuotaAuditCreate) createSpec() (*ResearchGroupQuotaAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &ResearchGroupQuotaAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(researchgroupquotaaudit.Table, sqlgraph.NewFieldSpec(researchgroupquotaaudit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.MemberID(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldMemberID, field.TypeInt64, value)
		_node.MemberID = &value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldActorUserID, field.TypeInt64, value)
		_node.ActorUserID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.AmountUsd(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldAmountUsd, field.TypeFloat64, value)
		_node.AmountUsd = &value
	}
	if value, ok := _c.mutation.PreviousValueUsd(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldPreviousValueUsd, field.TypeFloat64, value)
		_node.PreviousValueUsd = &value
	}
	if value, ok := _c.mutation.NewValueUsd(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldNewValueUsd, field.TypeFloat64, value)
		_node.NewValueUsd = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(researchgroupquotaaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ResearchGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   researchgroupquotaaudit.ResearchGroupTable,
			Columns: []string{researchgroupquotaaudit.ResearchGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(researchgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResearchGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResearchGroupQuotaAudit.Create().
//		SetResearchGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResearchGroupQuotaAuditUpsert) {
//			SetResearchGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResearchGroupQuotaAuditCreate) OnConflict(opts ...sql.ConflictOption) *ResearchGroupQuotaAuditUpsertOne {
	_c.conflict = opts
	return &ResearchGroupQuotaAuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResearchGroupQuotaAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResearchGroupQuotaAuditCreate) OnConflictColumns(columns ...string) *ResearchGroupQuotaAuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResearchGroupQuotaAuditUpsertOne{
		create: _c,
	}
}

type (
	// ResearchGroupQuotaAuditUpsertOne is the builder for "upsert"-ing
	//  one ResearchGroupQuotaAudit node.
	ResearchGroupQuotaAuditUpsertOne struct {
		create *ResearchGroupQuotaAuditCreate
	}

	// ResearchGroupQuotaAuditUpsert is the "OnConflict" setter.
	ResearchGroupQuotaAuditUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResearchGroupQuotaAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResearchGroupQuotaAuditUpsertOne) UpdateNewValues() *ResearchGroupQuotaAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ResearchGroupID(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldResearchGroupID)
		}
		if _, exists := u.create.mutation.MemberID(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldMemberID)
		}
		if _, exists := u.create.mutation.ActorUserID(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldActorUserID)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldAction)
		}
		if _, exists := u.create.mutation.AmountUsd(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldAmountUsd)
		}
		if _, exists := u.create.mutation.PreviousValueUsd(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldPreviousValueUsd)
		}
		if _, exists := u.create.mutation.NewValueUsd(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldNewValueUsd)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldMetadata)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(researchgroupquotaaudit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResearchGroupQuotaAudit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResearchGroupQuotaAuditUpsertOne) Ignore() *ResearchGroupQuotaAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResearchGroupQuotaAuditUpsertOne) DoNothing() *ResearchGroupQuotaAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResearchGroupQuotaAuditCreate.OnConflict
// documentation for more info.
func (u *ResearchGroupQuotaAuditUpsertOne) Update(set func(*ResearchGroupQuotaAuditUpsert)) *ResearchGroupQuotaAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResearchGroupQuotaAuditUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ResearchGroupQuotaAuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResearchGroupQuotaAuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResearchGroupQuotaAuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResearchGroupQuotaAuditUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResearchGroupQuotaAuditUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResearchGroupQuotaAuditCreateBulk is the builder for creating many ResearchGroupQuotaAudit entities in bulk.
type ResearchGroupQuotaAuditCreateBulk struct {
	config
	err      error
	builders []*ResearchGroupQuotaAuditCreate
	conflict []sql.ConflictOption
}

// Save creates the ResearchGroupQuotaAudit entities in the database.
func (_c *ResearchGroupQuotaAuditCreateBulk) Save(ctx context.Context) ([]*ResearchGroupQuotaAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResearchGroupQuotaAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResearchGroupQuotaAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResearchGroupQuotaAuditCreateBulk) SaveX(ctx context.Context) []*ResearchGroupQuotaAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResearchGroupQuotaAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResearchGroupQuotaAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResearchGroupQuotaAudit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResearchGroupQuotaAuditUpsert) {
//			SetResearchGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResearchGroupQuotaAuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResearchGroupQuotaAuditUpsertBulk {
	_c.conflict = opts
	return &ResearchGroupQuotaAuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResearchGroupQuotaAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResearchGroupQuotaAuditCreateBulk) OnConflictColumns(columns ...string) *ResearchGroupQuotaAuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResearchGroupQuotaAuditUpsertBulk{
		create: _c,
	}
}

// ResearchGroupQuotaAuditUpsertBulk is the builder for "upsert"-ing
// a bulk of ResearchGroupQuotaAudit nodes.
type ResearchGroupQuotaAuditUpsertBulk struct {
	create *ResearchGroupQuotaAuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResearchGroupQuotaAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResearchGroupQuotaAuditUpsertBulk) UpdateNewValues() *ResearchGroupQuotaAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ResearchGroupID(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldResearchGroupID)
			}
			if _, exists := b.mutation.MemberID(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldMemberID)
			}
			if _, exists := b.mutation.ActorUserID(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldActorUserID)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldAction)
			}
			if _, exists := b.mutation.AmountUsd(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldAmountUsd)
			}
			if _, exists := b.mutation.PreviousValueUsd(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldPreviousValueUsd)
			}
			if _, exists := b.mutation.NewValueUsd(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldNewValueUsd)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldMetadata)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(researchgroupquotaaudit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResearchGroupQuotaAudit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResearchGroupQuotaAuditUpsertBulk) Ignore() *ResearchGroupQuotaAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResearchGroupQuotaAuditUpsertBulk) DoNothing() *ResearchGroupQuotaAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResearchGroupQuotaAuditCreateBulk.OnConflict
// documentation for more info.
func (u *ResearchGroupQuotaAuditUpsertBulk) Update(set func(*ResearchGroupQuotaAuditUpsert)) *ResearchGroupQuotaAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResearchGroupQuotaAuditUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ResearchGroupQuotaAuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResearchGroupQuotaAuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResearchGroupQuotaAuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResearchGroupQuotaAuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
