// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/researchgroup"
	"github.com/Wei-Shaw/sub2api/ent/researchgroupmember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResearchGroupMember is the model entity for the ResearchGroupMember schema.
type ResearchGroupMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ResearchGroupID holds the value of the "research_group_id" field.
	ResearchGroupID int64 `json:"research_group_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd float64 `json:"monthly_limit_usd,omitempty"`
	// MonthlyUsageUsd holds the value of the "monthly_usage_usd" field.
	MonthlyUsageUsd float64 `json:"monthly_usage_usd,omitempty"`
	// MonthlyReservedUsd holds the value of the "monthly_reserved_usd" field.
	MonthlyReservedUsd float64 `json:"monthly_reserved_usd,omitempty"`
	// UsageWindowStart holds the value of the "usage_window_start" field.
	UsageWindowStart time.Time `json:"usage_window_start,omitempty"`
	// InvitedAt holds the value of the "invited_at" field.
	InvitedAt time.Time `json:"invited_at,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	// PausedAt holds the value of the "paused_at" field.
	PausedAt *time.Time `json:"paused_at,omitempty"`
	// RemovedAt holds the value of the "removed_at" field.
	RemovedAt *time.Time `json:"removed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResearchGroupMemberQuery when eager-loading is set.
	Edges        ResearchGroupMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResearchGroupMemberEdges holds the relations/edges for other nodes in the graph.
type ResearchGroupMemberEdges struct {
	// ResearchGroup holds the value of the research_group edge.
	ResearchGroup *ResearchGroup `json:"research_group,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ResearchGroupOrErr returns the ResearchGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResearchGroupMemberEdges) ResearchGroupOrErr() (*ResearchGroup, error) {
	if e.ResearchGroup != nil {
		return e.ResearchGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: researchgroup.Label}
	}
	return nil, &NotLoadedError{edge: "research_group"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResearchGroupMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResearchGroupMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case researchgroupmember.FieldMonthlyLimitUsd, researchgroupmember.FieldMonthlyUsageUsd, researchgroupmember.FieldMonthlyReservedUsd:
			values[i] = new(sql.NullFloat64)
		case researchgroupmember.FieldID, researchgroupmember.FieldResearchGroupID, researchgroupmember.FieldUserID:
			values[i] = new(sql.NullInt64)
		case researchgroupmember.FieldStatus:
			values[i] = new(sql.NullString)
		case researchgroupmember.FieldUsageWindowStart, researchgroupmember.FieldInvitedAt, researchgroupmember.FieldAcceptedAt, researchgroupmember.FieldPausedAt, researchgroupmember.FieldRemovedAt, researchgroupmember.FieldCreatedAt, researchgroupmember.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResearchGroupMember fields.
func (_m *ResearchGroupMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case researchgroupmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case researchgroupmember.FieldResearchGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field research_group_id", values[i])
			} else if value.Valid {
				_m.ResearchGroupID = value.Int64
			}
		case researchgroupmember.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case researchgroupmember.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case researchgroupmember.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = value.Float64
			}
		case researchgroupmember.FieldMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_usage_usd", values[i])
			} else if value.Valid {
				_m.MonthlyUsageUsd = value.Float64
			}
		case researchgroupmember.FieldMonthlyReservedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_reserved_usd", values[i])
			} else if value.Valid {
				_m.MonthlyReservedUsd = value.Float64
			}
		case researchgroupmember.FieldUsageWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field usage_window_start", values[i])
			} else if value.Valid {
				_m.UsageWindowStart = value.Time
			}
		case researchgroupmember.FieldInvitedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field invited_at", values[i])
			} else if value.Valid {
				_m.InvitedAt = value.Time
			}
		case researchgroupmember.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = new(time.Time)
				*_m.AcceptedAt = value.Time
			}
		case researchgroupmember.FieldPausedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paused_at", values[i])
			} else if value.Valid {
				_m.PausedAt = new(time.Time)
				*_m.PausedAt = value.Time
			}
		case researchgroupmember.FieldRemovedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field removed_at", values[i])
			} else if value.Valid {
				_m.RemovedAt = new(time.Time)
				*_m.RemovedAt = value.Time
			}
		case researchgroupmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case researchgroupmember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResearchGroupMember.
// This includes values selected through modifiers, order, etc.
func (_m *ResearchGroupMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryResearchGroup queries the "research_group" edge of the ResearchGroupMember entity.
func (_m *ResearchGroupMember) QueryResearchGroup() *ResearchGroupQuery {
	return NewResearchGroupMemberClient(_m.config).QueryResearchGroup(_m)
}

// QueryUser queries the "user" edge of the ResearchGroupMember entity.
func (_m *ResearchGroupMember) QueryUser() *UserQuery {
	return NewResearchGroupMemberClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ResearchGroupMember.
// Note that you need to call ResearchGroupMember.Unwrap() before calling this method if this ResearchGroupMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResearchGroupMember) Update() *ResearchGroupMemberUpdateOne {
	return NewResearchGroupMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResearchGroupMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResearchGroupMember) Unwrap() *ResearchGroupMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResearchGroupMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResearchGroupMember) String() string {
	var builder strings.Builder
	builder.WriteString("ResearchGroupMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("research_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResearchGroupID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("monthly_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_reserved_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyReservedUsd))
	builder.WriteString(", ")
	builder.WriteString("usage_window_start=")
	builder.WriteString(_m.UsageWindowStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("invited_at=")
	builder.WriteString(_m.InvitedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PausedAt; v != nil {
		builder.WriteString("paused_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RemovedAt; v != nil {
		builder.WriteString("removed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ResearchGroupMembers is a parsable slice of ResearchGroupMember.
type ResearchGroupMembers []*ResearchGroupMember
