// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/researchgroup"
	"github.com/Wei-Shaw/sub2api/ent/researchgroupmember"
	"github.com/Wei-Shaw/sub2api/ent/researchgroupquotaaudit"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ResearchGroupQuery is the builder for querying ResearchGroup entities.
type ResearchGroupQuery struct {
	config
	ctx                 *QueryContext
	order               []researchgroup.OrderOption
	inters              []Interceptor
	predicates          []predicate.ResearchGroup
	withOwner           *UserQuery
	withMembers         *ResearchGroupMemberQuery
	withQuotaAudits     *ResearchGroupQuotaAuditQuery
	withFundedUsageLogs *UsageLogQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResearchGroupQuery builder.
func (_q *ResearchGroupQuery) Where(ps ...predicate.ResearchGroup) *ResearchGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ResearchGroupQuery) Limit(limit int) *ResearchGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ResearchGroupQuery) Offset(offset int) *ResearchGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ResearchGroupQuery) Unique(unique bool) *ResearchGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ResearchGroupQuery) Order(o ...researchgroup.OrderOption) *ResearchGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *ResearchGroupQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(researchgroup.Table, researchgroup.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, researchgroup.OwnerTable, researchgroup.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMembers chains the current query on the "members" edge.
func (_q *ResearchGroupQuery) QueryMembers() *ResearchGroupMemberQuery {
	query := (&ResearchGroupMemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(researchgroup.Table, researchgroup.FieldID, selector),
			sqlgraph.To(researchgroupmember.Table, researchgroupmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, researchgroup.MembersTable, researchgroup.MembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuotaAudits chains the current query on the "quota_audits" edge.
func (_q *ResearchGroupQuery) QueryQuotaAudits() *ResearchGroupQuotaAuditQuery {
	query := (&ResearchGroupQuotaAuditClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(researchgroup.Table, researchgroup.FieldID, selector),
			sqlgraph.To(researchgroupquotaaudit.Table, researchgroupquotaaudit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, researchgroup.QuotaAuditsTable, researchgroup.QuotaAuditsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFundedUsageLogs chains the current query on the "funded_usage_logs" edge.
func (_q *ResearchGroupQuery) QueryFundedUsageLogs() *UsageLogQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(researchgroup.Table, researchgroup.FieldID, selector),
			sqlgraph.To(usagelog.Table, usagelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, researchgroup.FundedUsageLogsTable, researchgroup.FundedUsageLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ResearchGroup entity from the query.
// Returns a *NotFoundError when no ResearchGroup was found.
func (_q *ResearchGroupQuery) First(ctx context.Context) (*ResearchGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{researchgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ResearchGroupQuery) FirstX(ctx context.Context) *ResearchGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ResearchGroup ID from the query.
// Returns a *NotFoundError when no ResearchGroup ID was found.
func (_q *ResearchGroupQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{researchgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ResearchGroupQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ResearchGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ResearchGroup entity is found.
// Returns a *NotFoundError when no ResearchGroup entities are found.
func (_q *ResearchGroupQuery) Only(ctx context.Context) (*ResearchGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{researchgroup.Label}
	default:
		return nil, &NotSingularError{researchgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ResearchGroupQuery) OnlyX(ctx context.Context) *ResearchGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ResearchGroup ID in the query.
// Returns a *NotSingularError when more than one ResearchGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ResearchGroupQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{researchgroup.Label}
	default:
		err = &NotSingularError{researchgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ResearchGroupQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ResearchGroups.
func (_q *ResearchGroupQuery) All(ctx context.Context) ([]*ResearchGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ResearchGroup, *ResearchGroupQuery]()
	return withInterceptors[[]*ResearchGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ResearchGroupQuery) AllX(ctx context.Context) []*ResearchGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ResearchGroup IDs.
func (_q *ResearchGroupQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(researchgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ResearchGroupQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ResearchGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ResearchGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ResearchGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ResearchGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ResearchGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResearchGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ResearchGroupQuery) Clone() *ResearchGroupQuery {
	if _q == nil {
		return nil
	}
	return &ResearchGroupQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]researchgroup.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.ResearchGroup{}, _q.predicates...),
		withOwner:           _q.withOwner.Clone(),
		withMembers:         _q.withMembers.Clone(),
		withQuotaAudits:     _q.withQuotaAudits.Clone(),
		withFundedUsageLogs: _q.withFundedUsageLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResearchGroupQuery) WithOwner(opts ...func(*UserQuery)) *ResearchGroupQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithMembers tells the query-builder to eager-load the nodes that are connected to
// the "members" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResearchGroupQuery) WithMembers(opts ...func(*ResearchGroupMemberQuery)) *ResearchGroupQuery {
	query := (&ResearchGroupMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMembers = query
	return _q
}

// WithQuotaAudits tells the query-builder to eager-load the nodes that are connected to
// the "quota_audits" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResearchGroupQuery) WithQuotaAudits(opts ...func(*ResearchGroupQuotaAuditQuery)) *ResearchGroupQuery {
	query := (&ResearchGroupQuotaAuditClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withQuotaAudits = query
	return _q
}

// WithFundedUsageLogs tells the query-builder to eager-load the nodes that are connected to
// the "funded_usage_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResearchGroupQuery) WithFundedUsageLogs(opts ...func(*UsageLogQuery)) *ResearchGroupQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFundedUsageLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ResearchGroup.Query().
//		GroupBy(researchgroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ResearchGroupQuery) GroupBy(field string, fields ...string) *ResearchGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResearchGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = researchgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ResearchGroup.Query().
//		Select(researchgroup.FieldName).
//		Scan(ctx, &v)
func (_q *ResearchGroupQuery) Select(fields ...string) *ResearchGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ResearchGroupSelect{ResearchGroupQuery: _q}
	sbuild.label = researchgroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResearchGroupSelect configured with the given aggregations.
func (_q *ResearchGroupQuery) Aggregate(fns ...AggregateFunc) *ResearchGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ResearchGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !researchgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ResearchGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ResearchGroup, error) {
	var (
		nodes       = []*ResearchGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withOwner != nil,
			_q.withMembers != nil,
			_q.withQuotaAudits != nil,
			_q.withFundedUsageLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ResearchGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ResearchGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *ResearchGroup, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMembers; query != nil {
		if err := _q.loadMembers(ctx, query, nodes,
			func(n *ResearchGroup) { n.Edges.Members = []*ResearchGroupMember{} },
			func(n *ResearchGroup, e *ResearchGroupMember) { n.Edges.Members = append(n.Edges.Members, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withQuotaAudits; query != nil {
		if err := _q.loadQuotaAudits(ctx, query, nodes,
			func(n *ResearchGroup) { n.Edges.QuotaAudits = []*ResearchGroupQuotaAudit{} },
			func(n *ResearchGroup, e *ResearchGroupQuotaAudit) {
				n.Edges.QuotaAudits = append(n.Edges.QuotaAudits, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withFundedUsageLogs; query != nil {
		if err := _q.loadFundedUsageLogs(ctx, query, nodes,
			func(n *ResearchGroup) { n.Edges.FundedUsageLogs = []*UsageLog{} },
			func(n *ResearchGroup, e *UsageLog) { n.Edges.FundedUsageLogs = append(n.Edges.FundedUsageLogs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ResearchGroupQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*ResearchGroup, init func(*ResearchGroup), assign func(*ResearchGroup, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ResearchGroup)
	for i := range nodes {
		if nodes[i].OwnerUserID == nil {
			continue
		}
		fk := *nodes[i].OwnerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ResearchGroupQuery) loadMembers(ctx context.Context, query *ResearchGroupMemberQuery, nodes []*ResearchGroup, init func(*ResearchGroup), assign func(*ResearchGroup, *ResearchGroupMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ResearchGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(researchgroupmember.FieldResearchGroupID)
	}
	query.Where(predicate.ResearchGroupMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(researchgroup.MembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ResearchGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "research_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ResearchGroupQuery) loadQuotaAudits(ctx context.Context, query *ResearchGroupQuotaAuditQuery, nodes []*ResearchGroup, init func(*ResearchGroup), assign func(*ResearchGroup, *ResearchGroupQuotaAudit)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ResearchGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(researchgroupquotaaudit.FieldResearchGroupID)
	}
	query.Where(predicate.ResearchGroupQuotaAudit(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(researchgroup.QuotaAuditsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ResearchGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "research_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ResearchGroupQuery) loadFundedUsageLogs(ctx context.Context, query *UsageLogQuery, nodes []*ResearchGroup, init func(*ResearchGroup), assign func(*ResearchGroup, *UsageLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ResearchGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagelog.FieldResearchGroupID)
	}
	query.Where(predicate.UsageLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(researchgroup.FundedUsageLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ResearchGroupID
		if fk == nil {
			return fmt.Errorf(`foreign-key "research_group_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "research_group_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ResearchGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ResearchGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(researchgroup.Table, researchgroup.Columns, sqlgraph.NewFieldSpec(researchgroup.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, researchgroup.FieldID)
		for i := range fields {
			if fields[i] != researchgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOwner != nil {
			_spec.Node.AddColumnOnce(researchgroup.FieldOwnerUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ResearchGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(researchgroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = researchgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ResearchGroupQuery) ForUpdate(opts ...sql.LockOption) *ResearchGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ResearchGroupQuery) ForShare(opts ...sql.LockOption) *ResearchGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ResearchGroupGroupBy is the group-by builder for ResearchGroup entities.
type ResearchGroupGroupBy struct {
	selector
	build *ResearchGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ResearchGroupGroupBy) Aggregate(fns ...AggregateFunc) *ResearchGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ResearchGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResearchGroupQuery, *ResearchGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ResearchGroupGroupBy) sqlScan(ctx context.Context, root *ResearchGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResearchGroupSelect is the builder for selecting fields of ResearchGroup entities.
type ResearchGroupSelect struct {
	*ResearchGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ResearchGroupSelect) Aggregate(fns ...AggregateFunc) *ResearchGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ResearchGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResearchGroupQuery, *ResearchGroupSelect](ctx, _s.ResearchGroupQuery, _s, _s.inters, v)
}

func (_s *ResearchGroupSelect) sqlScan(ctx context.Context, root *ResearchGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
