// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliateadminaudit"
)

// UserAffiliateAdminAuditCreate is the builder for creating a UserAffiliateAdminAudit entity.
type UserAffiliateAdminAuditCreate struct {
	config
	mutation *UserAffiliateAdminAuditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *UserAffiliateAdminAuditCreate) SetOperatorUserID(v int64) *UserAffiliateAdminAuditCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetTargetUserID sets the "target_user_id" field.
func (_c *UserAffiliateAdminAuditCreate) SetTargetUserID(v int64) *UserAffiliateAdminAuditCreate {
	_c.mutation.SetTargetUserID(v)
	return _c
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_c *UserAffiliateAdminAuditCreate) SetNillableTargetUserID(v *int64) *UserAffiliateAdminAuditCreate {
	if v != nil {
		_c.SetTargetUserID(*v)
	}
	return _c
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (_c *UserAffiliateAdminAuditCreate) SetWithdrawalID(v int64) *UserAffiliateAdminAuditCreate {
	_c.mutation.SetWithdrawalID(v)
	return _c
}

// SetNillableWithdrawalID sets the "withdrawal_id" field if the given value is not nil.
func (_c *UserAffiliateAdminAuditCreate) SetNillableWithdrawalID(v *int64) *UserAffiliateAdminAuditCreate {
	if v != nil {
		_c.SetWithdrawalID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *UserAffiliateAdminAuditCreate) SetAction(v string) *UserAffiliateAdminAuditCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *UserAffiliateAdminAuditCreate) SetIdempotencyKey(v string) *UserAffiliateAdminAuditCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *UserAffiliateAdminAuditCreate) SetNillableIdempotencyKey(v *string) *UserAffiliateAdminAuditCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetDetail sets the "detail" field.
func (_c *UserAffiliateAdminAuditCreate) SetDetail(v string) *UserAffiliateAdminAuditCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_c *UserAffiliateAdminAuditCreate) SetNillableDetail(v *string) *UserAffiliateAdminAuditCreate {
	if v != nil {
		_c.SetDetail(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAffiliateAdminAuditCreate) SetCreatedAt(v time.Time) *UserAffiliateAdminAuditCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAffiliateAdminAuditCreate) SetNillableCreatedAt(v *time.Time) *UserAffiliateAdminAuditCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the UserAffiliateAdminAuditMutation object of the builder.
func (_c *UserAffiliateAdminAuditCreate) Mutation() *UserAffiliateAdminAuditMutation {
	return _c.mutation
}

// Save creates the UserAffiliateAdminAudit in the database.
func (_c *UserAffiliateAdminAuditCreate) Save(ctx context.Context) (*UserAffiliateAdminAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAffiliateAdminAuditCreate) SaveX(ctx context.Context) *UserAffiliateAdminAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAffiliateAdminAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAffiliateAdminAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAffiliateAdminAuditCreate) defaults() {
	if _, ok := _c.mutation.Detail(); !ok {
		v := useraffiliateadminaudit.DefaultDetail
		_c.mutation.SetDetail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useraffiliateadminaudit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAffiliateAdminAuditCreate) check() error {
	if _, ok := _c.mutation.OperatorUserID(); !ok {
		return &ValidationError{Name: "operator_user_id", err: errors.New(`ent: missing required field "UserAffiliateAdminAudit.operator_user_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "UserAffiliateAdminAudit.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := useraffiliateadminaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateAdminAudit.action": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := useraffiliateadminaudit.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateAdminAudit.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "UserAffiliateAdminAudit.detail"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAffiliateAdminAudit.created_at"`)}
	}
	return nil
}

func (_c *UserAffiliateAdminAuditCreate) sqlSave(ctx context.Context) (*UserAffiliateAdminAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAffiliateAdminAuditCreate) createSpec() (*UserAffiliateAdminAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAffiliateAdminAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useraffiliateadminaudit.Table, sqlgraph.NewFieldSpec(useraffiliateadminaudit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = value
	}
	if value, ok := _c.mutation.TargetUserID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldTargetUserID, field.TypeInt64, value)
		_node.TargetUserID = &value
	}
	if value, ok := _c.mutation.WithdrawalID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldWithdrawalID, field.TypeInt64, value)
		_node.WithdrawalID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAffiliateAdminAudit.Create().
//		SetOperatorUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAffiliateAdminAuditUpsert) {
//			SetOperatorUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAffiliateAdminAuditCreate) OnConflict(opts ...sql.ConflictOption) *UserAffiliateAdminAuditUpsertOne {
	_c.conflict = opts
	return &UserAffiliateAdminAuditUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAffiliateAdminAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAffiliateAdminAuditCreate) OnConflictColumns(columns ...string) *UserAffiliateAdminAuditUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAffiliateAdminAuditUpsertOne{
		create: _c,
	}
}

type (
	// UserAffiliateAdminAuditUpsertOne is the builder for "upsert"-ing
	//  one UserAffiliateAdminAudit node.
	UserAffiliateAdminAuditUpsertOne struct {
		create *UserAffiliateAdminAuditCreate
	}

	// UserAffiliateAdminAuditUpsert is the "OnConflict" setter.
	UserAffiliateAdminAuditUpsert struct {
		*sql.UpdateSet
	}
)

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserAffiliateAdminAuditUpsert) SetOperatorUserID(v int64) *UserAffiliateAdminAuditUpsert {
	u.Set(useraffiliateadminaudit.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsert) UpdateOperatorUserID() *UserAffiliateAdminAuditUpsert {
	u.SetExcluded(useraffiliateadminaudit.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserAffiliateAdminAuditUpsert) AddOperatorUserID(v int64) *UserAffiliateAdminAuditUpsert {
	u.Add(useraffiliateadminaudit.FieldOperatorUserID, v)
	return u
}

// SetTargetUserID sets the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsert) SetTargetUserID(v int64) *UserAffiliateAdminAuditUpsert {
	u.Set(useraffiliateadminaudit.FieldTargetUserID, v)
	return u
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsert) UpdateTargetUserID() *UserAffiliateAdminAuditUpsert {
	u.SetExcluded(useraffiliateadminaudit.FieldTargetUserID)
	return u
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsert) AddTargetUserID(v int64) *UserAffiliateAdminAuditUpsert {
	u.Add(useraffiliateadminaudit.FieldTargetUserID, v)
	return u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsert) ClearTargetUserID() *UserAffiliateAdminAuditUpsert {
	u.SetNull(useraffiliateadminaudit.FieldTargetUserID)
	return u
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsert) SetWithdrawalID(v int64) *UserAffiliateAdminAuditUpsert {
	u.Set(useraffiliateadminaudit.FieldWithdrawalID, v)
	return u
}

// UpdateWithdrawalID sets the "withdrawal_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsert) UpdateWithdrawalID() *UserAffiliateAdminAuditUpsert {
	u.SetExcluded(useraffiliateadminaudit.FieldWithdrawalID)
	return u
}

// AddWithdrawalID adds v to the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsert) AddWithdrawalID(v int64) *UserAffiliateAdminAuditUpsert {
	u.Add(useraffiliateadminaudit.FieldWithdrawalID, v)
	return u
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsert) ClearWithdrawalID() *UserAffiliateAdminAuditUpsert {
	u.SetNull(useraffiliateadminaudit.FieldWithdrawalID)
	return u
}

// SetAction sets the "action" field.
func (u *UserAffiliateAdminAuditUpsert) SetAction(v string) *UserAffiliateAdminAuditUpsert {
	u.Set(useraffiliateadminaudit.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsert) UpdateAction() *UserAffiliateAdminAuditUpsert {
	u.SetExcluded(useraffiliateadminaudit.FieldAction)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *UserAffiliateAdminAuditUpsert) SetIdempotencyKey(v string) *UserAffiliateAdminAuditUpsert {
	u.Set(useraffiliateadminaudit.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsert) UpdateIdempotencyKey() *UserAffiliateAdminAuditUpsert {
	u.SetExcluded(useraffiliateadminaudit.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *UserAffiliateAdminAuditUpsert) ClearIdempotencyKey() *UserAffiliateAdminAuditUpsert {
	u.SetNull(useraffiliateadminaudit.FieldIdempotencyKey)
	return u
}

// SetDetail sets the "detail" field.
func (u *UserAffiliateAdminAuditUpsert) SetDetail(v string) *UserAffiliateAdminAuditUpsert {
	u.Set(useraffiliateadminaudit.FieldDetail, v)
	return u
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsert) UpdateDetail() *UserAffiliateAdminAuditUpsert {
	u.SetExcluded(useraffiliateadminaudit.FieldDetail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserAffiliateAdminAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAffiliateAdminAuditUpsertOne) UpdateNewValues() *UserAffiliateAdminAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useraffiliateadminaudit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAffiliateAdminAudit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserAffiliateAdminAuditUpsertOne) Ignore() *UserAffiliateAdminAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAffiliateAdminAuditUpsertOne) DoNothing() *UserAffiliateAdminAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAffiliateAdminAuditCreate.OnConflict
// documentation for more info.
func (u *UserAffiliateAdminAuditUpsertOne) Update(set func(*UserAffiliateAdminAuditUpsert)) *UserAffiliateAdminAuditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAffiliateAdminAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) SetOperatorUserID(v int64) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) AddOperatorUserID(v int64) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertOne) UpdateOperatorUserID() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateOperatorUserID()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) SetTargetUserID(v int64) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetTargetUserID(v)
	})
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) AddTargetUserID(v int64) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.AddTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertOne) UpdateTargetUserID() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) ClearTargetUserID() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.ClearTargetUserID()
	})
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) SetWithdrawalID(v int64) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetWithdrawalID(v)
	})
}

// AddWithdrawalID adds v to the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) AddWithdrawalID(v int64) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.AddWithdrawalID(v)
	})
}

// UpdateWithdrawalID sets the "withdrawal_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertOne) UpdateWithdrawalID() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateWithdrawalID()
	})
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsertOne) ClearWithdrawalID() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.ClearWithdrawalID()
	})
}

// SetAction sets the "action" field.
func (u *UserAffiliateAdminAuditUpsertOne) SetAction(v string) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertOne) UpdateAction() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateAction()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *UserAffiliateAdminAuditUpsertOne) SetIdempotencyKey(v string) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertOne) UpdateIdempotencyKey() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *UserAffiliateAdminAuditUpsertOne) ClearIdempotencyKey() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetDetail sets the "detail" field.
func (u *UserAffiliateAdminAuditUpsertOne) SetDetail(v string) *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertOne) UpdateDetail() *UserAffiliateAdminAuditUpsertOne {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateDetail()
	})
}

// Exec executes the query.
func (u *UserAffiliateAdminAuditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAffiliateAdminAuditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAffiliateAdminAuditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserAffiliateAdminAuditUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserAffiliateAdminAuditUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserAffiliateAdminAuditCreateBulk is the builder for creating many UserAffiliateAdminAudit entities in bulk.
type UserAffiliateAdminAuditCreateBulk struct {
	config
	err      error
	builders []*UserAffiliateAdminAuditCreate
	conflict []sql.ConflictOption
}

// Save creates the UserAffiliateAdminAudit entities in the database.
func (_c *UserAffiliateAdminAuditCreateBulk) Save(ctx context.Context) ([]*UserAffiliateAdminAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAffiliateAdminAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAffiliateAdminAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAffiliateAdminAuditCreateBulk) SaveX(ctx context.Context) []*UserAffiliateAdminAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAffiliateAdminAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAffiliateAdminAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAffiliateAdminAudit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAffiliateAdminAuditUpsert) {
//			SetOperatorUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAffiliateAdminAuditCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserAffiliateAdminAuditUpsertBulk {
	_c.conflict = opts
	return &UserAffiliateAdminAuditUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAffiliateAdminAudit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAffiliateAdminAuditCreateBulk) OnConflictColumns(columns ...string) *UserAffiliateAdminAuditUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAffiliateAdminAuditUpsertBulk{
		create: _c,
	}
}

// UserAffiliateAdminAuditUpsertBulk is the builder for "upsert"-ing
// a bulk of UserAffiliateAdminAudit nodes.
type UserAffiliateAdminAuditUpsertBulk struct {
	create *UserAffiliateAdminAuditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserAffiliateAdminAudit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAffiliateAdminAuditUpsertBulk) UpdateNewValues() *UserAffiliateAdminAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useraffiliateadminaudit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAffiliateAdminAudit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserAffiliateAdminAuditUpsertBulk) Ignore() *UserAffiliateAdminAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAffiliateAdminAuditUpsertBulk) DoNothing() *UserAffiliateAdminAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAffiliateAdminAuditCreateBulk.OnConflict
// documentation for more info.
func (u *UserAffiliateAdminAuditUpsertBulk) Update(set func(*UserAffiliateAdminAuditUpsert)) *UserAffiliateAdminAuditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAffiliateAdminAuditUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) SetOperatorUserID(v int64) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) AddOperatorUserID(v int64) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertBulk) UpdateOperatorUserID() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateOperatorUserID()
	})
}

// SetTargetUserID sets the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) SetTargetUserID(v int64) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetTargetUserID(v)
	})
}

// AddTargetUserID adds v to the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) AddTargetUserID(v int64) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.AddTargetUserID(v)
	})
}

// UpdateTargetUserID sets the "target_user_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertBulk) UpdateTargetUserID() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateTargetUserID()
	})
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) ClearTargetUserID() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.ClearTargetUserID()
	})
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) SetWithdrawalID(v int64) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetWithdrawalID(v)
	})
}

// AddWithdrawalID adds v to the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) AddWithdrawalID(v int64) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.AddWithdrawalID(v)
	})
}

// UpdateWithdrawalID sets the "withdrawal_id" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertBulk) UpdateWithdrawalID() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateWithdrawalID()
	})
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (u *UserAffiliateAdminAuditUpsertBulk) ClearWithdrawalID() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.ClearWithdrawalID()
	})
}

// SetAction sets the "action" field.
func (u *UserAffiliateAdminAuditUpsertBulk) SetAction(v string) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertBulk) UpdateAction() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateAction()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *UserAffiliateAdminAuditUpsertBulk) SetIdempotencyKey(v string) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertBulk) UpdateIdempotencyKey() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *UserAffiliateAdminAuditUpsertBulk) ClearIdempotencyKey() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetDetail sets the "detail" field.
func (u *UserAffiliateAdminAuditUpsertBulk) SetDetail(v string) *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *UserAffiliateAdminAuditUpsertBulk) UpdateDetail() *UserAffiliateAdminAuditUpsertBulk {
	return u.Update(func(s *UserAffiliateAdminAuditUpsert) {
		s.UpdateDetail()
	})
}

// Exec executes the query.
func (u *UserAffiliateAdminAuditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserAffiliateAdminAuditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAffiliateAdminAuditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAffiliateAdminAuditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
