// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliateadminaudit"
)

// UserAffiliateAdminAuditUpdate is the builder for updating UserAffiliateAdminAudit entities.
type UserAffiliateAdminAuditUpdate struct {
	config
	hooks    []Hook
	mutation *UserAffiliateAdminAuditMutation
}

// Where appends a list predicates to the UserAffiliateAdminAuditUpdate builder.
func (_u *UserAffiliateAdminAuditUpdate) Where(ps ...predicate.UserAffiliateAdminAudit) *UserAffiliateAdminAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *UserAffiliateAdminAuditUpdate) SetOperatorUserID(v int64) *UserAffiliateAdminAuditUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdate) SetNillableOperatorUserID(v *int64) *UserAffiliateAdminAuditUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *UserAffiliateAdminAuditUpdate) AddOperatorUserID(v int64) *UserAffiliateAdminAuditUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *UserAffiliateAdminAuditUpdate) SetTargetUserID(v int64) *UserAffiliateAdminAuditUpdate {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdate) SetNillableTargetUserID(v *int64) *UserAffiliateAdminAuditUpdate {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *UserAffiliateAdminAuditUpdate) AddTargetUserID(v int64) *UserAffiliateAdminAuditUpdate {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (_u *UserAffiliateAdminAuditUpdate) ClearTargetUserID() *UserAffiliateAdminAuditUpdate {
	_u.mutation.ClearTargetUserID()
	return _u
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (_u *UserAffiliateAdminAuditUpdate) SetWithdrawalID(v int64) *UserAffiliateAdminAuditUpdate {
	_u.mutation.ResetWithdrawalID()
	_u.mutation.SetWithdrawalID(v)
	return _u
}

// SetNillableWithdrawalID sets the "withdrawal_id" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdate) SetNillableWithdrawalID(v *int64) *UserAffiliateAdminAuditUpdate {
	if v != nil {
		_u.SetWithdrawalID(*v)
	}
	return _u
}

// AddWithdrawalID adds value to the "withdrawal_id" field.
func (_u *UserAffiliateAdminAuditUpdate) AddWithdrawalID(v int64) *UserAffiliateAdminAuditUpdate {
	_u.mutation.AddWithdrawalID(v)
	return _u
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (_u *UserAffiliateAdminAuditUpdate) ClearWithdrawalID() *UserAffiliateAdminAuditUpdate {
	_u.mutation.ClearWithdrawalID()
	return _u
}

// SetAction sets the "action" field.
func (_u *UserAffiliateAdminAuditUpdate) SetAction(v string) *UserAffiliateAdminAuditUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdate) SetNillableAction(v *string) *UserAffiliateAdminAuditUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *UserAffiliateAdminAuditUpdate) SetIdempotencyKey(v string) *UserAffiliateAdminAuditUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdate) SetNillableIdempotencyKey(v *string) *UserAffiliateAdminAuditUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *UserAffiliateAdminAuditUpdate) ClearIdempotencyKey() *UserAffiliateAdminAuditUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *UserAffiliateAdminAuditUpdate) SetDetail(v string) *UserAffiliateAdminAuditUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdate) SetNillableDetail(v *string) *UserAffiliateAdminAuditUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// Mutation returns the UserAffiliateAdminAuditMutation object of the builder.
func (_u *UserAffiliateAdminAuditUpdate) Mutation() *UserAffiliateAdminAuditMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAffiliateAdminAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateAdminAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAffiliateAdminAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateAdminAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateAdminAuditUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := useraffiliateadminaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateAdminAudit.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := useraffiliateadminaudit.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateAdminAudit.idempotency_key": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateAdminAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliateadminaudit.Table, useraffiliateadminaudit.Columns, sqlgraph.NewFieldSpec(useraffiliateadminaudit.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(useraffiliateadminaudit.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldTargetUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(useraffiliateadminaudit.FieldTargetUserID, field.TypeInt64, value)
	}
	if _u.mutation.TargetUserIDCleared() {
		_spec.ClearField(useraffiliateadminaudit.FieldTargetUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.WithdrawalID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldWithdrawalID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWithdrawalID(); ok {
		_spec.AddField(useraffiliateadminaudit.FieldWithdrawalID, field.TypeInt64, value)
	}
	if _u.mutation.WithdrawalIDCleared() {
		_spec.ClearField(useraffiliateadminaudit.FieldWithdrawalID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(useraffiliateadminaudit.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldDetail, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliateadminaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAffiliateAdminAuditUpdateOne is the builder for updating a single UserAffiliateAdminAudit entity.
type UserAffiliateAdminAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAffiliateAdminAuditMutation
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) SetOperatorUserID(v int64) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdateOne) SetNillableOperatorUserID(v *int64) *UserAffiliateAdminAuditUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) AddOperatorUserID(v int64) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) SetTargetUserID(v int64) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdateOne) SetNillableTargetUserID(v *int64) *UserAffiliateAdminAuditUpdateOne {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) AddTargetUserID(v int64) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) ClearTargetUserID() *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.ClearTargetUserID()
	return _u
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) SetWithdrawalID(v int64) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.ResetWithdrawalID()
	_u.mutation.SetWithdrawalID(v)
	return _u
}

// SetNillableWithdrawalID sets the "withdrawal_id" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdateOne) SetNillableWithdrawalID(v *int64) *UserAffiliateAdminAuditUpdateOne {
	if v != nil {
		_u.SetWithdrawalID(*v)
	}
	return _u
}

// AddWithdrawalID adds value to the "withdrawal_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) AddWithdrawalID(v int64) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.AddWithdrawalID(v)
	return _u
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (_u *UserAffiliateAdminAuditUpdateOne) ClearWithdrawalID() *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.ClearWithdrawalID()
	return _u
}

// SetAction sets the "action" field.
func (_u *UserAffiliateAdminAuditUpdateOne) SetAction(v string) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdateOne) SetNillableAction(v *string) *UserAffiliateAdminAuditUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *UserAffiliateAdminAuditUpdateOne) SetIdempotencyKey(v string) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdateOne) SetNillableIdempotencyKey(v *string) *UserAffiliateAdminAuditUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *UserAffiliateAdminAuditUpdateOne) ClearIdempotencyKey() *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *UserAffiliateAdminAuditUpdateOne) SetDetail(v string) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *UserAffiliateAdminAuditUpdateOne) SetNillableDetail(v *string) *UserAffiliateAdminAuditUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// Mutation returns the UserAffiliateAdminAuditMutation object of the builder.
func (_u *UserAffiliateAdminAuditUpdateOne) Mutation() *UserAffiliateAdminAuditMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAffiliateAdminAuditUpdate builder.
func (_u *UserAffiliateAdminAuditUpdateOne) Where(ps ...predicate.UserAffiliateAdminAudit) *UserAffiliateAdminAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAffiliateAdminAuditUpdateOne) Select(field string, fields ...string) *UserAffiliateAdminAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAffiliateAdminAudit entity.
func (_u *UserAffiliateAdminAuditUpdateOne) Save(ctx context.Context) (*UserAffiliateAdminAudit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateAdminAuditUpdateOne) SaveX(ctx context.Context) *UserAffiliateAdminAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAffiliateAdminAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateAdminAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateAdminAuditUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := useraffiliateadminaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateAdminAudit.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := useraffiliateadminaudit.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateAdminAudit.idempotency_key": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateAdminAuditUpdateOne) sqlSave(ctx context.Context) (_node *UserAffiliateAdminAudit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliateadminaudit.Table, useraffiliateadminaudit.Columns, sqlgraph.NewFieldSpec(useraffiliateadminaudit.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAffiliateAdminAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraffiliateadminaudit.FieldID)
		for _, f := range fields {
			if !useraffiliateadminaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraffiliateadminaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(useraffiliateadminaudit.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldTargetUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(useraffiliateadminaudit.FieldTargetUserID, field.TypeInt64, value)
	}
	if _u.mutation.TargetUserIDCleared() {
		_spec.ClearField(useraffiliateadminaudit.FieldTargetUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.WithdrawalID(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldWithdrawalID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWithdrawalID(); ok {
		_spec.AddField(useraffiliateadminaudit.FieldWithdrawalID, field.TypeInt64, value)
	}
	if _u.mutation.WithdrawalIDCleared() {
		_spec.ClearField(useraffiliateadminaudit.FieldWithdrawalID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(useraffiliateadminaudit.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(useraffiliateadminaudit.FieldDetail, field.TypeString, value)
	}
	_node = &UserAffiliateAdminAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliateadminaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
