// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliatewithdrawal"
)

// UserAffiliateWithdrawalUpdate is the builder for updating UserAffiliateWithdrawal entities.
type UserAffiliateWithdrawalUpdate struct {
	config
	hooks    []Hook
	mutation *UserAffiliateWithdrawalMutation
}

// Where appends a list predicates to the UserAffiliateWithdrawalUpdate builder.
func (_u *UserAffiliateWithdrawalUpdate) Where(ps ...predicate.UserAffiliateWithdrawal) *UserAffiliateWithdrawalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAffiliateWithdrawalUpdate) SetUpdatedAt(v time.Time) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAffiliateWithdrawalUpdate) SetUserID(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableUserID(v *int64) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAffiliateWithdrawalUpdate) AddUserID(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserAffiliateWithdrawalUpdate) SetAmount(v float64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableAmount(v *float64) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserAffiliateWithdrawalUpdate) AddAmount(v float64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserAffiliateWithdrawalUpdate) SetStatus(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableStatus(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentAccountID sets the "payment_account_id" field.
func (_u *UserAffiliateWithdrawalUpdate) SetPaymentAccountID(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.ResetPaymentAccountID()
	_u.mutation.SetPaymentAccountID(v)
	return _u
}

// SetNillablePaymentAccountID sets the "payment_account_id" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillablePaymentAccountID(v *int64) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetPaymentAccountID(*v)
	}
	return _u
}

// AddPaymentAccountID adds value to the "payment_account_id" field.
func (_u *UserAffiliateWithdrawalUpdate) AddPaymentAccountID(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.AddPaymentAccountID(v)
	return _u
}

// ClearPaymentAccountID clears the value of the "payment_account_id" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearPaymentAccountID() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearPaymentAccountID()
	return _u
}

// SetPaymentAccountType sets the "payment_account_type" field.
func (_u *UserAffiliateWithdrawalUpdate) SetPaymentAccountType(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetPaymentAccountType(v)
	return _u
}

// SetNillablePaymentAccountType sets the "payment_account_type" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillablePaymentAccountType(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetPaymentAccountType(*v)
	}
	return _u
}

// SetPaymentDetailsEncrypted sets the "payment_details_encrypted" field.
func (_u *UserAffiliateWithdrawalUpdate) SetPaymentDetailsEncrypted(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetPaymentDetailsEncrypted(v)
	return _u
}

// SetNillablePaymentDetailsEncrypted sets the "payment_details_encrypted" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillablePaymentDetailsEncrypted(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetPaymentDetailsEncrypted(*v)
	}
	return _u
}

// SetPaymentAccountSummary sets the "payment_account_summary" field.
func (_u *UserAffiliateWithdrawalUpdate) SetPaymentAccountSummary(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetPaymentAccountSummary(v)
	return _u
}

// SetNillablePaymentAccountSummary sets the "payment_account_summary" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillablePaymentAccountSummary(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetPaymentAccountSummary(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *UserAffiliateWithdrawalUpdate) SetIdempotencyKey(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableIdempotencyKey(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearIdempotencyKey() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *UserAffiliateWithdrawalUpdate) SetSubmittedAt(v time.Time) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableSubmittedAt(v *time.Time) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *UserAffiliateWithdrawalUpdate) SetReviewedAt(v time.Time) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableReviewedAt(v *time.Time) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearReviewedAt() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *UserAffiliateWithdrawalUpdate) SetReviewedBy(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableReviewedBy(v *int64) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *UserAffiliateWithdrawalUpdate) AddReviewedBy(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearReviewedBy() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *UserAffiliateWithdrawalUpdate) SetPaidAt(v time.Time) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillablePaidAt(v *time.Time) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearPaidAt() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetPaidBy sets the "paid_by" field.
func (_u *UserAffiliateWithdrawalUpdate) SetPaidBy(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.ResetPaidBy()
	_u.mutation.SetPaidBy(v)
	return _u
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillablePaidBy(v *int64) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetPaidBy(*v)
	}
	return _u
}

// AddPaidBy adds value to the "paid_by" field.
func (_u *UserAffiliateWithdrawalUpdate) AddPaidBy(v int64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.AddPaidBy(v)
	return _u
}

// ClearPaidBy clears the value of the "paid_by" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearPaidBy() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearPaidBy()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *UserAffiliateWithdrawalUpdate) SetCanceledAt(v time.Time) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableCanceledAt(v *time.Time) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearCanceledAt() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *UserAffiliateWithdrawalUpdate) SetCancelReason(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableCancelReason(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearCancelReason() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearCancelReason()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *UserAffiliateWithdrawalUpdate) SetRejectReason(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableRejectReason(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearRejectReason() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetActualCurrency sets the "actual_currency" field.
func (_u *UserAffiliateWithdrawalUpdate) SetActualCurrency(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetActualCurrency(v)
	return _u
}

// SetNillableActualCurrency sets the "actual_currency" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableActualCurrency(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetActualCurrency(*v)
	}
	return _u
}

// ClearActualCurrency clears the value of the "actual_currency" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearActualCurrency() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearActualCurrency()
	return _u
}

// SetActualAmount sets the "actual_amount" field.
func (_u *UserAffiliateWithdrawalUpdate) SetActualAmount(v float64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.ResetActualAmount()
	_u.mutation.SetActualAmount(v)
	return _u
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableActualAmount(v *float64) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetActualAmount(*v)
	}
	return _u
}

// AddActualAmount adds value to the "actual_amount" field.
func (_u *UserAffiliateWithdrawalUpdate) AddActualAmount(v float64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.AddActualAmount(v)
	return _u
}

// ClearActualAmount clears the value of the "actual_amount" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearActualAmount() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearActualAmount()
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *UserAffiliateWithdrawalUpdate) SetExchangeRate(v float64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableExchangeRate(v *float64) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *UserAffiliateWithdrawalUpdate) AddExchangeRate(v float64) *UserAffiliateWithdrawalUpdate {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// ClearExchangeRate clears the value of the "exchange_rate" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearExchangeRate() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearExchangeRate()
	return _u
}

// SetExternalReference sets the "external_reference" field.
func (_u *UserAffiliateWithdrawalUpdate) SetExternalReference(v string) *UserAffiliateWithdrawalUpdate {
	_u.mutation.SetExternalReference(v)
	return _u
}

// SetNillableExternalReference sets the "external_reference" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdate) SetNillableExternalReference(v *string) *UserAffiliateWithdrawalUpdate {
	if v != nil {
		_u.SetExternalReference(*v)
	}
	return _u
}

// ClearExternalReference clears the value of the "external_reference" field.
func (_u *UserAffiliateWithdrawalUpdate) ClearExternalReference() *UserAffiliateWithdrawalUpdate {
	_u.mutation.ClearExternalReference()
	return _u
}

// Mutation returns the UserAffiliateWithdrawalMutation object of the builder.
func (_u *UserAffiliateWithdrawalUpdate) Mutation() *UserAffiliateWithdrawalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAffiliateWithdrawalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateWithdrawalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAffiliateWithdrawalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateWithdrawalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAffiliateWithdrawalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraffiliatewithdrawal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateWithdrawalUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := useraffiliatewithdrawal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAccountType(); ok {
		if err := useraffiliatewithdrawal.PaymentAccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_account_type", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.payment_account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAccountSummary(); ok {
		if err := useraffiliatewithdrawal.PaymentAccountSummaryValidator(v); err != nil {
			return &ValidationError{Name: "payment_account_summary", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.payment_account_summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := useraffiliatewithdrawal.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualCurrency(); ok {
		if err := useraffiliatewithdrawal.ActualCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "actual_currency", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.actual_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalReference(); ok {
		if err := useraffiliatewithdrawal.ExternalReferenceValidator(v); err != nil {
			return &ValidationError{Name: "external_reference", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.external_reference": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateWithdrawalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliatewithdrawal.Table, useraffiliatewithdrawal.Columns, sqlgraph.NewFieldSpec(useraffiliatewithdrawal.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentAccountID(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentAccountID(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldPaymentAccountID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentAccountIDCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldPaymentAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaymentAccountType(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentAccountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentDetailsEncrypted(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentDetailsEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentAccountSummary(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentAccountSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidBy(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaidBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaidBy(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldPaidBy, field.TypeInt64, value)
	}
	if _u.mutation.PaidByCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldPaidBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldCancelReason, field.TypeString, value)
	}
	if _u.mutation.CancelReasonCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldCancelReason, field.TypeString)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.ActualCurrency(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldActualCurrency, field.TypeString, value)
	}
	if _u.mutation.ActualCurrencyCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldActualCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.ActualAmount(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualAmount(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldActualAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ActualAmountCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldActualAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldExchangeRate, field.TypeFloat64, value)
	}
	if _u.mutation.ExchangeRateCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldExchangeRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExternalReference(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldExternalReference, field.TypeString, value)
	}
	if _u.mutation.ExternalReferenceCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldExternalReference, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliatewithdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAffiliateWithdrawalUpdateOne is the builder for updating a single UserAffiliateWithdrawal entity.
type UserAffiliateWithdrawalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAffiliateWithdrawalMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetUpdatedAt(v time.Time) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetUserID(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableUserID(v *int64) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAffiliateWithdrawalUpdateOne) AddUserID(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetAmount(v float64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableAmount(v *float64) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserAffiliateWithdrawalUpdateOne) AddAmount(v float64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetStatus(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableStatus(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentAccountID sets the "payment_account_id" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetPaymentAccountID(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ResetPaymentAccountID()
	_u.mutation.SetPaymentAccountID(v)
	return _u
}

// SetNillablePaymentAccountID sets the "payment_account_id" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillablePaymentAccountID(v *int64) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaymentAccountID(*v)
	}
	return _u
}

// AddPaymentAccountID adds value to the "payment_account_id" field.
func (_u *UserAffiliateWithdrawalUpdateOne) AddPaymentAccountID(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.AddPaymentAccountID(v)
	return _u
}

// ClearPaymentAccountID clears the value of the "payment_account_id" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearPaymentAccountID() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearPaymentAccountID()
	return _u
}

// SetPaymentAccountType sets the "payment_account_type" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetPaymentAccountType(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetPaymentAccountType(v)
	return _u
}

// SetNillablePaymentAccountType sets the "payment_account_type" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillablePaymentAccountType(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaymentAccountType(*v)
	}
	return _u
}

// SetPaymentDetailsEncrypted sets the "payment_details_encrypted" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetPaymentDetailsEncrypted(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetPaymentDetailsEncrypted(v)
	return _u
}

// SetNillablePaymentDetailsEncrypted sets the "payment_details_encrypted" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillablePaymentDetailsEncrypted(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaymentDetailsEncrypted(*v)
	}
	return _u
}

// SetPaymentAccountSummary sets the "payment_account_summary" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetPaymentAccountSummary(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetPaymentAccountSummary(v)
	return _u
}

// SetNillablePaymentAccountSummary sets the "payment_account_summary" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillablePaymentAccountSummary(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaymentAccountSummary(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetIdempotencyKey(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableIdempotencyKey(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearIdempotencyKey() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetSubmittedAt(v time.Time) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableSubmittedAt(v *time.Time) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetReviewedAt(v time.Time) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableReviewedAt(v *time.Time) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearReviewedAt() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetReviewedBy(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableReviewedBy(v *int64) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *UserAffiliateWithdrawalUpdateOne) AddReviewedBy(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearReviewedBy() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetPaidAt(v time.Time) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillablePaidAt(v *time.Time) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearPaidAt() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetPaidBy sets the "paid_by" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetPaidBy(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ResetPaidBy()
	_u.mutation.SetPaidBy(v)
	return _u
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillablePaidBy(v *int64) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaidBy(*v)
	}
	return _u
}

// AddPaidBy adds value to the "paid_by" field.
func (_u *UserAffiliateWithdrawalUpdateOne) AddPaidBy(v int64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.AddPaidBy(v)
	return _u
}

// ClearPaidBy clears the value of the "paid_by" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearPaidBy() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearPaidBy()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetCanceledAt(v time.Time) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableCanceledAt(v *time.Time) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearCanceledAt() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetCancelReason(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableCancelReason(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearCancelReason() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearCancelReason()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetRejectReason(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableRejectReason(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearRejectReason() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetActualCurrency sets the "actual_currency" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetActualCurrency(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetActualCurrency(v)
	return _u
}

// SetNillableActualCurrency sets the "actual_currency" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableActualCurrency(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetActualCurrency(*v)
	}
	return _u
}

// ClearActualCurrency clears the value of the "actual_currency" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearActualCurrency() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearActualCurrency()
	return _u
}

// SetActualAmount sets the "actual_amount" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetActualAmount(v float64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ResetActualAmount()
	_u.mutation.SetActualAmount(v)
	return _u
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableActualAmount(v *float64) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetActualAmount(*v)
	}
	return _u
}

// AddActualAmount adds value to the "actual_amount" field.
func (_u *UserAffiliateWithdrawalUpdateOne) AddActualAmount(v float64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.AddActualAmount(v)
	return _u
}

// ClearActualAmount clears the value of the "actual_amount" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearActualAmount() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearActualAmount()
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetExchangeRate(v float64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableExchangeRate(v *float64) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *UserAffiliateWithdrawalUpdateOne) AddExchangeRate(v float64) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// ClearExchangeRate clears the value of the "exchange_rate" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearExchangeRate() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearExchangeRate()
	return _u
}

// SetExternalReference sets the "external_reference" field.
func (_u *UserAffiliateWithdrawalUpdateOne) SetExternalReference(v string) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.SetExternalReference(v)
	return _u
}

// SetNillableExternalReference sets the "external_reference" field if the given value is not nil.
func (_u *UserAffiliateWithdrawalUpdateOne) SetNillableExternalReference(v *string) *UserAffiliateWithdrawalUpdateOne {
	if v != nil {
		_u.SetExternalReference(*v)
	}
	return _u
}

// ClearExternalReference clears the value of the "external_reference" field.
func (_u *UserAffiliateWithdrawalUpdateOne) ClearExternalReference() *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.ClearExternalReference()
	return _u
}

// Mutation returns the UserAffiliateWithdrawalMutation object of the builder.
func (_u *UserAffiliateWithdrawalUpdateOne) Mutation() *UserAffiliateWithdrawalMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAffiliateWithdrawalUpdate builder.
func (_u *UserAffiliateWithdrawalUpdateOne) Where(ps ...predicate.UserAffiliateWithdrawal) *UserAffiliateWithdrawalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAffiliateWithdrawalUpdateOne) Select(field string, fields ...string) *UserAffiliateWithdrawalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAffiliateWithdrawal entity.
func (_u *UserAffiliateWithdrawalUpdateOne) Save(ctx context.Context) (*UserAffiliateWithdrawal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateWithdrawalUpdateOne) SaveX(ctx context.Context) *UserAffiliateWithdrawal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAffiliateWithdrawalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateWithdrawalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAffiliateWithdrawalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraffiliatewithdrawal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateWithdrawalUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := useraffiliatewithdrawal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAccountType(); ok {
		if err := useraffiliatewithdrawal.PaymentAccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_account_type", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.payment_account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAccountSummary(); ok {
		if err := useraffiliatewithdrawal.PaymentAccountSummaryValidator(v); err != nil {
			return &ValidationError{Name: "payment_account_summary", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.payment_account_summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := useraffiliatewithdrawal.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualCurrency(); ok {
		if err := useraffiliatewithdrawal.ActualCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "actual_currency", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.actual_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalReference(); ok {
		if err := useraffiliatewithdrawal.ExternalReferenceValidator(v); err != nil {
			return &ValidationError{Name: "external_reference", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateWithdrawal.external_reference": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateWithdrawalUpdateOne) sqlSave(ctx context.Context) (_node *UserAffiliateWithdrawal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliatewithdrawal.Table, useraffiliatewithdrawal.Columns, sqlgraph.NewFieldSpec(useraffiliatewithdrawal.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAffiliateWithdrawal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraffiliatewithdrawal.FieldID)
		for _, f := range fields {
			if !useraffiliatewithdrawal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraffiliatewithdrawal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentAccountID(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentAccountID(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldPaymentAccountID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentAccountIDCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldPaymentAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaymentAccountType(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentAccountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentDetailsEncrypted(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentDetailsEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentAccountSummary(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaymentAccountSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidBy(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldPaidBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaidBy(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldPaidBy, field.TypeInt64, value)
	}
	if _u.mutation.PaidByCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldPaidBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldCancelReason, field.TypeString, value)
	}
	if _u.mutation.CancelReasonCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldCancelReason, field.TypeString)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.ActualCurrency(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldActualCurrency, field.TypeString, value)
	}
	if _u.mutation.ActualCurrencyCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldActualCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.ActualAmount(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualAmount(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldActualAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ActualAmountCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldActualAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(useraffiliatewithdrawal.FieldExchangeRate, field.TypeFloat64, value)
	}
	if _u.mutation.ExchangeRateCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldExchangeRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ExternalReference(); ok {
		_spec.SetField(useraffiliatewithdrawal.FieldExternalReference, field.TypeString, value)
	}
	if _u.mutation.ExternalReferenceCleared() {
		_spec.ClearField(useraffiliatewithdrawal.FieldExternalReference, field.TypeString)
	}
	_node = &UserAffiliateWithdrawal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliatewithdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
