package handler

import (
	"strconv"
	"github.com/Wei-Shaw/sub2api/internal/handler/dto"
	"github.com/Wei-Shaw/sub2api/internal/pkg/response"
	middleware2 "github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/gin-gonic/gin"
)

func (h *UserHandler) ListAffiliatePaymentAccounts(c *gin.Context){subject,ok:=middleware2.GetAuthSubjectFromContext(c);if !ok{response.Unauthorized(c,"User not authenticated");return};items,err:=h.affiliatePayoutService.ListPaymentAccounts(c.Request.Context(),subject.UserID);if err!=nil{response.ErrorFrom(c,err);return};response.Success(c,items)}
func (h *UserHandler) CreateAffiliatePaymentAccount(c *gin.Context){subject,ok:=middleware2.GetAuthSubjectFromContext(c);if !ok{response.Unauthorized(c,"User not authenticated");return};var req dto.AffiliatePaymentAccountRequest;if err:=c.ShouldBindJSON(&req);err!=nil{response.BadRequest(c,"Invalid request: "+err.Error());return};item,err:=h.affiliatePayoutService.SavePaymentAccount(c.Request.Context(),subject.UserID,0,paymentAccountInput(req));if err!=nil{response.ErrorFrom(c,err);return};response.Success(c,item)}
func (h *UserHandler) UpdateAffiliatePaymentAccount(c *gin.Context){subject,ok:=middleware2.GetAuthSubjectFromContext(c);if !ok{response.Unauthorized(c,"User not authenticated");return};id,err:=strconv.ParseInt(c.Param("id"),10,64);if err!=nil||id<=0{response.BadRequest(c,"Invalid payment account id");return};var req dto.AffiliatePaymentAccountRequest;if err=c.ShouldBindJSON(&req);err!=nil{response.BadRequest(c,"Invalid request: "+err.Error());return};item,err:=h.affiliatePayoutService.SavePaymentAccount(c.Request.Context(),subject.UserID,id,paymentAccountInput(req));if err!=nil{response.ErrorFrom(c,err);return};response.Success(c,item)}
func (h *UserHandler) DeleteAffiliatePaymentAccount(c *gin.Context){subject,ok:=middleware2.GetAuthSubjectFromContext(c);if !ok{response.Unauthorized(c,"User not authenticated");return};id,err:=strconv.ParseInt(c.Param("id"),10,64);if err!=nil||id<=0{response.BadRequest(c,"Invalid payment account id");return};if err=h.affiliatePayoutService.DeletePaymentAccount(c.Request.Context(),subject.UserID,id);err!=nil{response.ErrorFrom(c,err);return};response.Success(c,gin.H{"id":id})}
func (h *UserHandler) ListAffiliateWithdrawals(c *gin.Context){subject,ok:=middleware2.GetAuthSubjectFromContext(c);if !ok{response.Unauthorized(c,"User not authenticated");return};page,pageSize:=response.ParsePagination(c);items,total,err:=h.affiliatePayoutService.ListUserWithdrawals(c.Request.Context(),subject.UserID,page,pageSize);if err!=nil{response.ErrorFrom(c,err);return};response.Paginated(c,items,total,page,pageSize)}
func (h *UserHandler) CreateAffiliateWithdrawal(c *gin.Context){subject,ok:=middleware2.GetAuthSubjectFromContext(c);if !ok{response.Unauthorized(c,"User not authenticated");return};var req dto.CreateAffiliateWithdrawalRequest;if err:=c.ShouldBindJSON(&req);err!=nil{response.BadRequest(c,"Invalid request: "+err.Error());return};item,err:=h.affiliatePayoutService.CreateWithdrawal(c.Request.Context(),subject.UserID,req.PaymentAccountID,req.Amount,c.GetHeader("Idempotency-Key"));if err!=nil{response.ErrorFrom(c,err);return};response.Success(c,item)}
func (h *UserHandler) CancelAffiliateWithdrawal(c *gin.Context){subject,ok:=middleware2.GetAuthSubjectFromContext(c);if !ok{response.Unauthorized(c,"User not authenticated");return};id,err:=strconv.ParseInt(c.Param("id"),10,64);if err!=nil||id<=0{response.BadRequest(c,"Invalid withdrawal id");return};item,err:=h.affiliatePayoutService.CancelWithdrawal(c.Request.Context(),subject.UserID,id);if err!=nil{response.ErrorFrom(c,err);return};response.Success(c,item)}
func paymentAccountInput(req dto.AffiliatePaymentAccountRequest)service.AffiliatePaymentAccountInput{return service.AffiliatePaymentAccountInput{Type:req.Type,AccountName:req.AccountName,AccountNumber:req.AccountNumber,BankName:req.BankName,USDTNetwork:req.USDTNetwork,WalletAddress:req.WalletAddress,IsDefault:req.IsDefault}}
