export const enCodexGuide = {
  heroBadge: 'Codex quickstart',
  title: 'Codex setup and usage guide',
  description:
    'Install Codex for the terminal or VS Code, connect it to your ISAC AI API key, and learn the essential commands for daily project work.',
  actions: {
    openKeys: 'Open API Keys',
    officialDocs: 'Official Codex docs'
  },
  quickStart: {
    title: 'Four steps to your first task',
    items: [
      'Create or select an API key',
      'Install Codex CLI or the IDE extension',
      'Run the generated setup command',
      'Open a project and start Codex'
    ]
  },
  install: {
    eyebrow: 'Step 1 · Install',
    title: 'Install Codex on your machine',
    body:
      'The CLI is the fastest way to verify your environment. The VS Code extension uses the same Codex configuration and credentials.',
    prerequisiteTitle: 'Check Node.js and npm',
    prerequisiteBody:
      'If either command is missing, install a current Node.js LTS release from the official Node.js website, then reopen your terminal.',
    cliTitle: 'Install the Codex CLI',
    cliBody: 'Install the official npm package globally, then confirm the codex command is available.',
    ideTitle: 'Use Codex in VS Code',
    ideBody:
      'Open Extensions, search for “Codex – OpenAI’s coding agent,” install the official OpenAI extension, and reload VS Code.',
    idePoints: [
      'Open the folder you want Codex to work in.',
      'The extension and CLI share the same ~/.codex configuration.',
      'After changing API settings, start a new Codex session or reload the extension.'
    ]
  },
  configure: {
    eyebrow: 'Step 2 · Configure',
    title: 'Connect Codex to your ISAC AI API key',
    body:
      'Use the setup command generated by the API Keys page. It selects the current recommended model and writes the provider and credential files for your operating system.',
    warningTitle: 'Run the command in a terminal',
    warningBody:
      'The copied content is a complete terminal command, not an API key. Never paste it into an API Key or token input.',
    steps: [
      {
        title: 'Choose a key and client',
        body: 'Open API Keys, select Use, then choose Codex CLI or Codex CLI (WebSocket).'
      },
      {
        title: 'Choose your operating system',
        body: 'Select macOS/Linux or Windows, copy the one-click setup command, and run it in that system’s terminal.'
      },
      {
        title: 'Restart and verify',
        body: 'Restart Codex or reload VS Code. For Remote SSH, run the command in the connected remote terminal, not on your laptop.'
      }
    ],
    filesTitle: 'Files written by the setup command',
    filesBody:
      'The CLI and IDE extension read these shared files. Treat auth.json like a password and never commit it.',
    ccSwitchAction: 'Need CC-Switch instead? Open its guide'
  },
  use: {
    eyebrow: 'Step 3 · Use',
    title: 'Start working in a project',
    body:
      'Run Codex from the project directory. Start interactively for normal work, resume context when needed, or use exec for a focused non-interactive task.',
    commands: [
      {
        title: 'Start an interactive session',
        body: 'Open the project directory and start Codex.'
      },
      {
        title: 'Resume the latest session',
        body: 'Continue the most recent session for the current directory.'
      },
      {
        title: 'Run one focused task',
        body: 'Use exec for scripts, CI, or a task that should finish without interaction.'
      },
      {
        title: 'Check available options',
        body: 'View commands and flags supported by your installed version.'
      }
    ],
    copy: 'Copy command',
    copied: 'Command copied'
  },
  bestPractices: {
    title: 'Get better results',
    items: [
      'Describe the goal, relevant files, constraints, and how success should be verified.',
      'Ask Codex to run the smallest relevant tests and review the final diff.',
      'Keep permissions scoped to the current workspace and review approval prompts.',
      'Never paste API keys into prompts, source files, screenshots, or Git commits.'
    ]
  },
  troubleshooting: {
    title: 'Common issues',
    items: [
      {
        title: 'codex command not found',
        body: 'Reopen the terminal, run npm prefix -g, and confirm the global npm bin directory is on PATH.'
      },
      {
        title: '401 or 403 authentication error',
        body: 'Generate a valid API key again, rerun the setup command, then use codex login status to inspect the active authentication method.'
      },
      {
        title: '404, 502, or unsupported endpoint',
        body: 'Return to API Keys and regenerate the Codex setup. If using CC-Switch, confirm the provider group and upstream API format match Codex.'
      },
      {
        title: 'VS Code still uses old settings',
        body: 'Reload the VS Code window or start a new Codex session after changing ~/.codex/config.toml.'
      },
      {
        title: 'Remote SSH uses local configuration',
        body: 'Run the one-click setup command in the VS Code terminal connected to the remote host. Local ~/.codex files do not configure the server.'
      },
      {
        title: 'Need a clean authentication check',
        body: 'Run codex login status. Use codex logout only when you intentionally want to clear the cached login.'
      }
    ]
  }
}

export const zhCodexGuide = {
  heroBadge: 'Codex 快速上手',
  title: 'Codex 配置与使用教程',
  description:
    '从安装 Codex CLI 或 VS Code 扩展，到接入本站 API 密钥，再到在项目中启动、恢复和自动执行任务，一页完成配置。',
  actions: {
    openKeys: '打开 API 密钥',
    officialDocs: 'Codex 官方文档'
  },
  quickStart: {
    title: '四步开始第一个任务',
    items: [
      '创建或选择一个 API 密钥',
      '安装 Codex CLI 或 IDE 扩展',
      '运行页面生成的一键配置命令',
      '打开项目并启动 Codex'
    ]
  },
  install: {
    eyebrow: '第 1 步 · 安装',
    title: '在电脑上安装 Codex',
    body: '建议先安装 CLI 验证环境；VS Code 扩展会和 CLI 共用同一套 Codex 配置与凭证。',
    prerequisiteTitle: '检查 Node.js 和 npm',
    prerequisiteBody:
      '如果任一命令不存在，请先从 Node.js 官网安装当前 LTS 版本，然后重新打开终端。',
    cliTitle: '安装 Codex CLI',
    cliBody: '全局安装 OpenAI 官方 npm 包，再确认 codex 命令可以正常运行。',
    ideTitle: '在 VS Code 中使用',
    ideBody:
      '打开扩展商店，搜索“Codex – OpenAI’s coding agent”，安装 OpenAI 官方扩展后重新加载 VS Code。',
    idePoints: [
      '在 VS Code 中打开希望 Codex 操作的项目文件夹。',
      '扩展与 CLI 共用 ~/.codex 下的配置。',
      '修改 API 配置后，请新建 Codex 会话或重新加载扩展。'
    ]
  },
  configure: {
    eyebrow: '第 2 步 · 配置',
    title: '使用 ISAC AI API 密钥配置 Codex',
    body:
      '直接使用 API 密钥页面生成的一键配置命令。命令会按当前推荐模型写入对应系统的服务商配置和凭证文件。',
    warningTitle: '请把命令粘贴到终端运行',
    warningBody: '复制的是一整条终端命令，不是 API Key；不要把它粘贴到 API Key 或令牌输入框。',
    steps: [
      {
        title: '选择密钥和客户端',
        body: '打开 API 密钥，点击“使用”，再选择 Codex CLI 或 Codex CLI (WebSocket)。'
      },
      {
        title: '选择操作系统',
        body: '选择 macOS/Linux 或 Windows，复制一键安装命令，并在对应系统的终端中运行。'
      },
      {
        title: '重启并验证',
        body: '重启 Codex 或重新加载 VS Code。使用 Remote SSH 时，必须在已连接服务器的远程终端中执行。'
      }
    ],
    filesTitle: '一键命令会写入的文件',
    filesBody: 'CLI 和 IDE 扩展会读取这些共享文件。auth.json 等同密码，请勿提交到 Git。',
    ccSwitchAction: '想使用 CC-Switch？查看对应教程'
  },
  use: {
    eyebrow: '第 3 步 · 使用',
    title: '在项目中开始工作',
    body:
      '在项目目录中运行 Codex。日常开发使用交互会话，需要保留上下文时恢复会话，脚本或单次任务则使用 exec。',
    commands: [
      {
        title: '启动交互会话',
        body: '进入项目目录并启动 Codex。'
      },
      {
        title: '恢复最近会话',
        body: '继续当前目录最近一次保存的会话。'
      },
      {
        title: '执行一个明确任务',
        body: '适合脚本、CI 或不需要持续交互的单次任务。'
      },
      {
        title: '查看可用选项',
        body: '查看当前安装版本支持的命令与参数。'
      }
    ],
    copy: '复制命令',
    copied: '命令已复制'
  },
  bestPractices: {
    title: '让 Codex 做得更好',
    items: [
      '说明目标、相关文件、约束条件，以及怎样才算完成。',
      '要求 Codex 运行最小范围的相关测试，并在完成后检查代码差异。',
      '把权限限制在当前工作区，认真阅读命令和文件修改审批。',
      '不要把 API Key 粘贴到提示词、源码、截图或 Git 提交中。'
    ]
  },
  troubleshooting: {
    title: '常见问题',
    items: [
      {
        title: '提示找不到 codex 命令',
        body: '重新打开终端，运行 npm prefix -g，并确认 npm 全局可执行目录已经加入 PATH。'
      },
      {
        title: '出现 401 或 403',
        body: '重新生成有效 API 密钥并再次运行一键配置命令，再用 codex login status 检查当前认证方式。'
      },
      {
        title: '出现 404、502 或端点不支持',
        body: '回到 API 密钥页面重新生成 Codex 配置。若使用 CC-Switch，请检查分组和上游 API 格式是否与 Codex 匹配。'
      },
      {
        title: 'VS Code 仍在使用旧配置',
        body: '修改 ~/.codex/config.toml 后，重新加载 VS Code 窗口或新建 Codex 会话。'
      },
      {
        title: 'Remote SSH 误用了本机配置',
        body: '请在 VS Code 已连接远程主机的终端中运行一键配置命令；本机 ~/.codex 文件不会配置服务器。'
      },
      {
        title: '想确认当前登录状态',
        body: '运行 codex login status。仅在确实要清除缓存登录时再运行 codex logout。'
      }
    ]
  }
}

export const zhHantCodexGuide = {
  heroBadge: 'Codex 快速入門',
  title: 'Codex 設定與使用教學',
  description:
    '從安裝 Codex CLI 或 VS Code 擴充套件，到串接本站 API 金鑰，再到啟動、恢復與自動執行專案任務。',
  actions: {
    openKeys: '開啟 API 金鑰',
    officialDocs: 'Codex 官方文件'
  },
  quickStart: {
    title: '四步開始第一個任務',
    items: [
      '建立或選擇 API 金鑰',
      '安裝 Codex CLI 或 IDE 擴充套件',
      '執行頁面產生的一鍵設定命令',
      '開啟專案並啟動 Codex'
    ]
  },
  install: {
    eyebrow: '第 1 步 · 安裝',
    title: '在電腦上安裝 Codex',
    body: '建議先用 CLI 驗證環境；VS Code 擴充套件會與 CLI 共用 Codex 設定和憑證。',
    prerequisiteTitle: '檢查 Node.js 和 npm',
    prerequisiteBody: '若任一命令不存在，請先從 Node.js 官網安裝目前的 LTS 版本，再重新開啟終端機。',
    cliTitle: '安裝 Codex CLI',
    cliBody: '全域安裝 OpenAI 官方 npm 套件，再確認 codex 命令可正常執行。',
    ideTitle: '在 VS Code 中使用',
    ideBody:
      '開啟擴充套件商店，搜尋「Codex – OpenAI’s coding agent」，安裝 OpenAI 官方擴充套件後重新載入 VS Code。',
    idePoints: [
      '在 VS Code 開啟希望 Codex 操作的專案資料夾。',
      '擴充套件與 CLI 共用 ~/.codex 設定。',
      '變更 API 設定後，請建立新 Codex 工作階段或重新載入擴充套件。'
    ]
  },
  configure: {
    eyebrow: '第 2 步 · 設定',
    title: '使用 ISAC AI API 金鑰設定 Codex',
    body: '使用 API 金鑰頁面產生的一鍵命令，寫入目前建議模型、服務商設定和憑證。',
    warningTitle: '請把命令貼到終端機執行',
    warningBody: '複製的是完整終端機命令，不是 API Key；請勿貼到 API Key 或權杖輸入框。',
    steps: [
      {
        title: '選擇金鑰與客戶端',
        body: '開啟 API 金鑰，按「使用」，再選 Codex CLI 或 Codex CLI (WebSocket)。'
      },
      {
        title: '選擇作業系統',
        body: '選 macOS/Linux 或 Windows，複製一鍵命令並在對應系統的終端機執行。'
      },
      {
        title: '重新啟動並驗證',
        body: '重新啟動 Codex 或載入 VS Code。Remote SSH 必須在已連線伺服器的遠端終端機執行。'
      }
    ],
    filesTitle: '一鍵命令會寫入的檔案',
    filesBody: 'CLI 與 IDE 擴充套件會讀取這些共用檔案。auth.json 等同密碼，請勿提交至 Git。',
    ccSwitchAction: '想使用 CC-Switch？查看對應教學'
  },
  use: {
    eyebrow: '第 3 步 · 使用',
    title: '在專案中開始工作',
    body: '在專案目錄執行 Codex；日常工作使用互動模式，保留脈絡時恢復工作階段，單次任務則使用 exec。',
    commands: [
      { title: '啟動互動工作階段', body: '進入專案目錄並啟動 Codex。' },
      { title: '恢復最近工作階段', body: '繼續目前目錄最近儲存的工作階段。' },
      { title: '執行明確任務', body: '適合腳本、CI 或不需持續互動的單次任務。' },
      { title: '查看可用選項', body: '查看目前版本支援的命令與參數。' }
    ],
    copy: '複製命令',
    copied: '命令已複製'
  },
  bestPractices: {
    title: '讓 Codex 做得更好',
    items: [
      '說明目標、相關檔案、限制條件與完成標準。',
      '要求執行最小範圍的相關測試，並在完成後檢查差異。',
      '將權限限制在目前工作區，仔細閱讀命令與檔案修改核准。',
      '不要把 API Key 貼到提示、原始碼、截圖或 Git 提交。'
    ]
  },
  troubleshooting: {
    title: '常見問題',
    items: [
      {
        title: '找不到 codex 命令',
        body: '重新開啟終端機，執行 npm prefix -g，並確認 npm 全域執行檔目錄已加入 PATH。'
      },
      {
        title: '出現 401 或 403',
        body: '重新產生有效 API 金鑰並執行一鍵設定，再用 codex login status 檢查目前驗證方式。'
      },
      {
        title: '出現 404、502 或端點不支援',
        body: '回到 API 金鑰頁重新產生 Codex 設定。若使用 CC-Switch，請檢查分組與上游 API 格式。'
      },
      {
        title: 'VS Code 仍使用舊設定',
        body: '修改 ~/.codex/config.toml 後，重新載入 VS Code 視窗或建立新 Codex 工作階段。'
      },
      {
        title: 'Remote SSH 使用了本機設定',
        body: '請在 VS Code 連線遠端主機的終端機執行一鍵命令；本機 ~/.codex 不會設定伺服器。'
      },
      {
        title: '確認目前登入狀態',
        body: '執行 codex login status。只有確定要清除快取登入時才執行 codex logout。'
      }
    ]
  }
}

export const jaCodexGuide = {
  heroBadge: 'Codex クイックスタート',
  title: 'Codex の設定と使い方',
  description:
    'Codex CLI または VS Code 拡張機能をインストールし、ISAC AI の API キーを設定して、プロジェクトで基本コマンドを使うまでを案内します。',
  actions: {
    openKeys: 'API キーを開く',
    officialDocs: 'Codex 公式ドキュメント'
  },
  quickStart: {
    title: '最初のタスクまでの 4 ステップ',
    items: [
      'API キーを作成または選択',
      'Codex CLI または IDE 拡張機能をインストール',
      '生成された設定コマンドを実行',
      'プロジェクトを開いて Codex を起動'
    ]
  },
  install: {
    eyebrow: 'ステップ 1 · インストール',
    title: 'Codex をインストール',
    body: 'まず CLI で環境を確認してください。VS Code 拡張機能は CLI と同じ設定と認証情報を共有します。',
    prerequisiteTitle: 'Node.js と npm を確認',
    prerequisiteBody:
      'コマンドが見つからない場合は Node.js 公式サイトから最新の LTS をインストールし、ターミナルを開き直します。',
    cliTitle: 'Codex CLI をインストール',
    cliBody: 'OpenAI 公式 npm パッケージをグローバルにインストールし、codex コマンドを確認します。',
    ideTitle: 'VS Code で使う',
    ideBody:
      '拡張機能で「Codex – OpenAI’s coding agent」を検索し、OpenAI 公式拡張機能をインストールして VS Code を再読み込みします。',
    idePoints: [
      'Codex で作業するプロジェクトフォルダーを開きます。',
      '拡張機能と CLI は ~/.codex の設定を共有します。',
      'API 設定を変更した後は新しいセッションを開始するか拡張機能を再読み込みします。'
    ]
  },
  configure: {
    eyebrow: 'ステップ 2 · 設定',
    title: 'ISAC AI API キーを設定',
    body: 'API キーページで生成されたワンクリック設定コマンドを使い、推奨モデル、プロバイダー、認証情報を書き込みます。',
    warningTitle: 'コマンドはターミナルで実行',
    warningBody: 'コピーされるのは完全なターミナルコマンドです。API Key やトークン欄には貼り付けないでください。',
    steps: [
      {
        title: 'キーとクライアントを選択',
        body: 'API キーの「使用」から Codex CLI または Codex CLI (WebSocket) を選びます。'
      },
      {
        title: 'OS を選択',
        body: 'macOS/Linux または Windows を選び、コマンドを対応するターミナルで実行します。'
      },
      {
        title: '再起動して確認',
        body: 'Codex または VS Code を再起動します。Remote SSH では接続先サーバーのターミナルで実行します。'
      }
    ],
    filesTitle: '設定コマンドが書き込むファイル',
    filesBody: 'CLI と IDE が共有します。auth.json はパスワードと同様に扱い、Git にコミットしないでください。',
    ccSwitchAction: 'CC-Switch を使う場合はガイドを開く'
  },
  use: {
    eyebrow: 'ステップ 3 · 使用',
    title: 'プロジェクトで作業を開始',
    body: 'プロジェクトディレクトリで Codex を実行します。通常は対話モード、継続には resume、単発処理には exec を使います。',
    commands: [
      { title: '対話セッションを開始', body: 'プロジェクトへ移動して Codex を起動します。' },
      { title: '直近のセッションを再開', body: '現在のディレクトリで最後のセッションを続けます。' },
      { title: '単一タスクを実行', body: 'スクリプト、CI、非対話の明確なタスクに使います。' },
      { title: 'オプションを確認', body: 'インストール済みバージョンのコマンドとフラグを表示します。' }
    ],
    copy: 'コマンドをコピー',
    copied: 'コマンドをコピーしました'
  },
  bestPractices: {
    title: 'より良い結果を得る',
    items: [
      '目的、関連ファイル、制約、完了条件を具体的に伝えます。',
      '必要最小限のテストを実行し、最後に差分を確認するよう依頼します。',
      '権限は現在のワークスペースに限定し、承認内容を確認します。',
      'API キーをプロンプト、ソース、画像、Git コミットに含めないでください。'
    ]
  },
  troubleshooting: {
    title: 'よくある問題',
    items: [
      {
        title: 'codex コマンドが見つからない',
        body: 'ターミナルを開き直し、npm prefix -g を実行してグローバル npm bin が PATH にあるか確認します。'
      },
      {
        title: '401 または 403',
        body: '有効な API キーで設定を再実行し、codex login status で現在の認証方式を確認します。'
      },
      {
        title: '404、502、未対応エンドポイント',
        body: 'API キーページで Codex 設定を再生成します。CC-Switch ではグループと上流 API 形式も確認します。'
      },
      {
        title: 'VS Code が古い設定を使う',
        body: '~/.codex/config.toml の変更後に VS Code を再読み込みするか新しいセッションを開始します。'
      },
      {
        title: 'Remote SSH でローカル設定が使われる',
        body: '接続先ホストの VS Code ターミナルで設定コマンドを実行します。ローカルの ~/.codex はサーバーに反映されません。'
      },
      {
        title: 'ログイン状態を確認したい',
        body: 'codex login status を実行します。キャッシュを消す必要がある場合だけ codex logout を使います。'
      }
    ]
  }
}

export const arCodexGuide = {
  heroBadge: 'بدء سريع مع Codex',
  title: 'دليل إعداد Codex واستخدامه',
  description:
    'ثبّت Codex في الطرفية أو VS Code، واربطه بمفتاح ISAC AI API، ثم استخدم الأوامر الأساسية للعمل داخل مشروعك.',
  actions: {
    openKeys: 'فتح مفاتيح API',
    officialDocs: 'وثائق Codex الرسمية'
  },
  quickStart: {
    title: 'أربع خطوات لأول مهمة',
    items: [
      'إنشاء مفتاح API أو اختياره',
      'تثبيت Codex CLI أو إضافة IDE',
      'تشغيل أمر الإعداد الذي أنشأته الصفحة',
      'فتح المشروع وتشغيل Codex'
    ]
  },
  install: {
    eyebrow: 'الخطوة 1 · التثبيت',
    title: 'ثبّت Codex على جهازك',
    body: 'ابدأ بالواجهة الطرفية للتحقق من البيئة. تشترك إضافة VS Code مع CLI في إعدادات Codex وبيانات الاعتماد.',
    prerequisiteTitle: 'تحقق من Node.js و npm',
    prerequisiteBody:
      'إذا كان أحد الأمرين غير موجود، فثبّت إصدار LTS الحالي من موقع Node.js الرسمي ثم أعد فتح الطرفية.',
    cliTitle: 'تثبيت Codex CLI',
    cliBody: 'ثبّت حزمة npm الرسمية من OpenAI بصورة عامة ثم تحقق من توفر أمر codex.',
    ideTitle: 'الاستخدام في VS Code',
    ideBody:
      'افتح الإضافات وابحث عن “Codex – OpenAI’s coding agent”، وثبّت إضافة OpenAI الرسمية ثم أعد تحميل VS Code.',
    idePoints: [
      'افتح مجلد المشروع الذي تريد أن يعمل فيه Codex.',
      'تشارك الإضافة وCLI إعدادات ~/.codex نفسها.',
      'بعد تغيير إعداد API، ابدأ جلسة Codex جديدة أو أعد تحميل الإضافة.'
    ]
  },
  configure: {
    eyebrow: 'الخطوة 2 · الإعداد',
    title: 'اربط Codex بمفتاح ISAC AI API',
    body: 'استخدم أمر الإعداد بنقرة واحدة من صفحة مفاتيح API لكتابة النموذج والموفر وبيانات الاعتماد المناسبة لنظامك.',
    warningTitle: 'شغّل الأمر في الطرفية',
    warningBody: 'المحتوى المنسوخ أمر طرفية كامل وليس مفتاح API. لا تلصقه في خانة مفتاح أو رمز.',
    steps: [
      {
        title: 'اختر المفتاح والعميل',
        body: 'افتح مفاتيح API واضغط استخدام، ثم اختر Codex CLI أو Codex CLI (WebSocket).'
      },
      {
        title: 'اختر نظام التشغيل',
        body: 'اختر macOS/Linux أو Windows، وانسخ الأمر وشغّله في طرفية ذلك النظام.'
      },
      {
        title: 'أعد التشغيل وتحقق',
        body: 'أعد تشغيل Codex أو تحميل VS Code. مع Remote SSH شغّل الأمر في طرفية الخادم المتصل.'
      }
    ],
    filesTitle: 'الملفات التي يكتبها أمر الإعداد',
    filesBody: 'يقرأ CLI وIDE هذه الملفات المشتركة. عامل auth.json ككلمة مرور ولا ترفعه إلى Git.',
    ccSwitchAction: 'هل تريد CC-Switch؟ افتح دليله'
  },
  use: {
    eyebrow: 'الخطوة 3 · الاستخدام',
    title: 'ابدأ العمل داخل مشروع',
    body: 'شغّل Codex من مجلد المشروع. استخدم الوضع التفاعلي عادة، وresume للمتابعة، وexec لمهمة واحدة غير تفاعلية.',
    commands: [
      { title: 'بدء جلسة تفاعلية', body: 'انتقل إلى المشروع ثم شغّل Codex.' },
      { title: 'استئناف أحدث جلسة', body: 'تابع آخر جلسة في المجلد الحالي.' },
      { title: 'تنفيذ مهمة محددة', body: 'مناسب للبرامج النصية وCI والمهام غير التفاعلية.' },
      { title: 'عرض الخيارات المتاحة', body: 'اعرض الأوامر والمعاملات التي يدعمها الإصدار المثبّت.' }
    ],
    copy: 'نسخ الأمر',
    copied: 'تم نسخ الأمر'
  },
  bestPractices: {
    title: 'احصل على نتائج أفضل',
    items: [
      'اذكر الهدف والملفات ذات الصلة والقيود وكيفية التحقق من النجاح.',
      'اطلب تشغيل أصغر مجموعة اختبارات مناسبة ومراجعة الفرق النهائي.',
      'احصر الصلاحيات في مساحة العمل الحالية وراجع طلبات الموافقة.',
      'لا تضع مفاتيح API في المطالبات أو الشفرة أو الصور أو التزامات Git.'
    ]
  },
  troubleshooting: {
    title: 'مشكلات شائعة',
    items: [
      {
        title: 'أمر codex غير موجود',
        body: 'أعد فتح الطرفية، وشغّل npm prefix -g، وتأكد أن مجلد npm العام موجود في PATH.'
      },
      {
        title: 'خطأ 401 أو 403',
        body: 'أنشئ مفتاح API صالحا وأعد تشغيل الإعداد، ثم استخدم codex login status لفحص طريقة المصادقة.'
      },
      {
        title: 'خطأ 404 أو 502 أو نقطة نهاية غير مدعومة',
        body: 'أعد إنشاء إعداد Codex من صفحة المفاتيح. مع CC-Switch تحقق من المجموعة وتنسيق API الصاعد.'
      },
      {
        title: 'VS Code يستخدم إعدادا قديما',
        body: 'بعد تعديل ~/.codex/config.toml أعد تحميل نافذة VS Code أو ابدأ جلسة Codex جديدة.'
      },
      {
        title: 'Remote SSH يستخدم الإعداد المحلي',
        body: 'شغّل أمر الإعداد في طرفية VS Code المتصلة بالمضيف البعيد؛ ملفات ~/.codex المحلية لا تضبط الخادم.'
      },
      {
        title: 'التحقق من حالة تسجيل الدخول',
        body: 'شغّل codex login status. استخدم codex logout فقط عندما تريد مسح تسجيل الدخول المحفوظ.'
      }
    ]
  }
}
