// Code generated by ent, DO NOT EDIT.

package conversationbranch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldSessionID, v))
}

// ParentBranchID applies equality check predicate on the "parent_branch_id" field. It's identical to ParentBranchIDEQ.
func ParentBranchID(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldParentBranchID, v))
}

// ForkEventID applies equality check predicate on the "fork_event_id" field. It's identical to ForkEventIDEQ.
func ForkEventID(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldForkEventID, v))
}

// HeadEventID applies equality check predicate on the "head_event_id" field. It's identical to HeadEventIDEQ.
func HeadEventID(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldHeadEventID, v))
}

// EventCount applies equality check predicate on the "event_count" field. It's identical to EventCountEQ.
func EventCount(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldEventCount, v))
}

// TailSequence applies equality check predicate on the "tail_sequence" field. It's identical to TailSequenceEQ.
func TailSequence(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldTailSequence, v))
}

// TailEventHash applies equality check predicate on the "tail_event_hash" field. It's identical to TailEventHashEQ.
func TailEventHash(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldTailEventHash, v))
}

// BranchReason applies equality check predicate on the "branch_reason" field. It's identical to BranchReasonEQ.
func BranchReason(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldBranchReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldCreatedAt, v))
}

// LastActiveAt applies equality check predicate on the "last_active_at" field. It's identical to LastActiveAtEQ.
func LastActiveAt(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldLastActiveAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldSessionID, v))
}

// ParentBranchIDEQ applies the EQ predicate on the "parent_branch_id" field.
func ParentBranchIDEQ(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldParentBranchID, v))
}

// ParentBranchIDNEQ applies the NEQ predicate on the "parent_branch_id" field.
func ParentBranchIDNEQ(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldParentBranchID, v))
}

// ParentBranchIDIn applies the In predicate on the "parent_branch_id" field.
func ParentBranchIDIn(vs ...uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldParentBranchID, vs...))
}

// ParentBranchIDNotIn applies the NotIn predicate on the "parent_branch_id" field.
func ParentBranchIDNotIn(vs ...uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldParentBranchID, vs...))
}

// ParentBranchIDGT applies the GT predicate on the "parent_branch_id" field.
func ParentBranchIDGT(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldParentBranchID, v))
}

// ParentBranchIDGTE applies the GTE predicate on the "parent_branch_id" field.
func ParentBranchIDGTE(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldParentBranchID, v))
}

// ParentBranchIDLT applies the LT predicate on the "parent_branch_id" field.
func ParentBranchIDLT(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldParentBranchID, v))
}

// ParentBranchIDLTE applies the LTE predicate on the "parent_branch_id" field.
func ParentBranchIDLTE(v uuid.UUID) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldParentBranchID, v))
}

// ParentBranchIDIsNil applies the IsNil predicate on the "parent_branch_id" field.
func ParentBranchIDIsNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIsNull(FieldParentBranchID))
}

// ParentBranchIDNotNil applies the NotNil predicate on the "parent_branch_id" field.
func ParentBranchIDNotNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotNull(FieldParentBranchID))
}

// ForkEventIDEQ applies the EQ predicate on the "fork_event_id" field.
func ForkEventIDEQ(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldForkEventID, v))
}

// ForkEventIDNEQ applies the NEQ predicate on the "fork_event_id" field.
func ForkEventIDNEQ(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldForkEventID, v))
}

// ForkEventIDIn applies the In predicate on the "fork_event_id" field.
func ForkEventIDIn(vs ...int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldForkEventID, vs...))
}

// ForkEventIDNotIn applies the NotIn predicate on the "fork_event_id" field.
func ForkEventIDNotIn(vs ...int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldForkEventID, vs...))
}

// ForkEventIDGT applies the GT predicate on the "fork_event_id" field.
func ForkEventIDGT(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldForkEventID, v))
}

// ForkEventIDGTE applies the GTE predicate on the "fork_event_id" field.
func ForkEventIDGTE(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldForkEventID, v))
}

// ForkEventIDLT applies the LT predicate on the "fork_event_id" field.
func ForkEventIDLT(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldForkEventID, v))
}

// ForkEventIDLTE applies the LTE predicate on the "fork_event_id" field.
func ForkEventIDLTE(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldForkEventID, v))
}

// ForkEventIDIsNil applies the IsNil predicate on the "fork_event_id" field.
func ForkEventIDIsNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIsNull(FieldForkEventID))
}

// ForkEventIDNotNil applies the NotNil predicate on the "fork_event_id" field.
func ForkEventIDNotNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotNull(FieldForkEventID))
}

// HeadEventIDEQ applies the EQ predicate on the "head_event_id" field.
func HeadEventIDEQ(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldHeadEventID, v))
}

// HeadEventIDNEQ applies the NEQ predicate on the "head_event_id" field.
func HeadEventIDNEQ(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldHeadEventID, v))
}

// HeadEventIDIn applies the In predicate on the "head_event_id" field.
func HeadEventIDIn(vs ...int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldHeadEventID, vs...))
}

// HeadEventIDNotIn applies the NotIn predicate on the "head_event_id" field.
func HeadEventIDNotIn(vs ...int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldHeadEventID, vs...))
}

// HeadEventIDGT applies the GT predicate on the "head_event_id" field.
func HeadEventIDGT(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldHeadEventID, v))
}

// HeadEventIDGTE applies the GTE predicate on the "head_event_id" field.
func HeadEventIDGTE(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldHeadEventID, v))
}

// HeadEventIDLT applies the LT predicate on the "head_event_id" field.
func HeadEventIDLT(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldHeadEventID, v))
}

// HeadEventIDLTE applies the LTE predicate on the "head_event_id" field.
func HeadEventIDLTE(v int64) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldHeadEventID, v))
}

// HeadEventIDIsNil applies the IsNil predicate on the "head_event_id" field.
func HeadEventIDIsNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIsNull(FieldHeadEventID))
}

// HeadEventIDNotNil applies the NotNil predicate on the "head_event_id" field.
func HeadEventIDNotNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotNull(FieldHeadEventID))
}

// EventCountEQ applies the EQ predicate on the "event_count" field.
func EventCountEQ(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldEventCount, v))
}

// EventCountNEQ applies the NEQ predicate on the "event_count" field.
func EventCountNEQ(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldEventCount, v))
}

// EventCountIn applies the In predicate on the "event_count" field.
func EventCountIn(vs ...int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldEventCount, vs...))
}

// EventCountNotIn applies the NotIn predicate on the "event_count" field.
func EventCountNotIn(vs ...int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldEventCount, vs...))
}

// EventCountGT applies the GT predicate on the "event_count" field.
func EventCountGT(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldEventCount, v))
}

// EventCountGTE applies the GTE predicate on the "event_count" field.
func EventCountGTE(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldEventCount, v))
}

// EventCountLT applies the LT predicate on the "event_count" field.
func EventCountLT(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldEventCount, v))
}

// EventCountLTE applies the LTE predicate on the "event_count" field.
func EventCountLTE(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldEventCount, v))
}

// TailSequenceEQ applies the EQ predicate on the "tail_sequence" field.
func TailSequenceEQ(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldTailSequence, v))
}

// TailSequenceNEQ applies the NEQ predicate on the "tail_sequence" field.
func TailSequenceNEQ(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldTailSequence, v))
}

// TailSequenceIn applies the In predicate on the "tail_sequence" field.
func TailSequenceIn(vs ...int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldTailSequence, vs...))
}

// TailSequenceNotIn applies the NotIn predicate on the "tail_sequence" field.
func TailSequenceNotIn(vs ...int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldTailSequence, vs...))
}

// TailSequenceGT applies the GT predicate on the "tail_sequence" field.
func TailSequenceGT(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldTailSequence, v))
}

// TailSequenceGTE applies the GTE predicate on the "tail_sequence" field.
func TailSequenceGTE(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldTailSequence, v))
}

// TailSequenceLT applies the LT predicate on the "tail_sequence" field.
func TailSequenceLT(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldTailSequence, v))
}

// TailSequenceLTE applies the LTE predicate on the "tail_sequence" field.
func TailSequenceLTE(v int) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldTailSequence, v))
}

// TailEventHashEQ applies the EQ predicate on the "tail_event_hash" field.
func TailEventHashEQ(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldTailEventHash, v))
}

// TailEventHashNEQ applies the NEQ predicate on the "tail_event_hash" field.
func TailEventHashNEQ(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldTailEventHash, v))
}

// TailEventHashIn applies the In predicate on the "tail_event_hash" field.
func TailEventHashIn(vs ...string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldTailEventHash, vs...))
}

// TailEventHashNotIn applies the NotIn predicate on the "tail_event_hash" field.
func TailEventHashNotIn(vs ...string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldTailEventHash, vs...))
}

// TailEventHashGT applies the GT predicate on the "tail_event_hash" field.
func TailEventHashGT(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldTailEventHash, v))
}

// TailEventHashGTE applies the GTE predicate on the "tail_event_hash" field.
func TailEventHashGTE(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldTailEventHash, v))
}

// TailEventHashLT applies the LT predicate on the "tail_event_hash" field.
func TailEventHashLT(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldTailEventHash, v))
}

// TailEventHashLTE applies the LTE predicate on the "tail_event_hash" field.
func TailEventHashLTE(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldTailEventHash, v))
}

// TailEventHashContains applies the Contains predicate on the "tail_event_hash" field.
func TailEventHashContains(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldContains(FieldTailEventHash, v))
}

// TailEventHashHasPrefix applies the HasPrefix predicate on the "tail_event_hash" field.
func TailEventHashHasPrefix(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldHasPrefix(FieldTailEventHash, v))
}

// TailEventHashHasSuffix applies the HasSuffix predicate on the "tail_event_hash" field.
func TailEventHashHasSuffix(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldHasSuffix(FieldTailEventHash, v))
}

// TailEventHashIsNil applies the IsNil predicate on the "tail_event_hash" field.
func TailEventHashIsNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIsNull(FieldTailEventHash))
}

// TailEventHashNotNil applies the NotNil predicate on the "tail_event_hash" field.
func TailEventHashNotNil() predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotNull(FieldTailEventHash))
}

// TailEventHashEqualFold applies the EqualFold predicate on the "tail_event_hash" field.
func TailEventHashEqualFold(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEqualFold(FieldTailEventHash, v))
}

// TailEventHashContainsFold applies the ContainsFold predicate on the "tail_event_hash" field.
func TailEventHashContainsFold(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldContainsFold(FieldTailEventHash, v))
}

// BranchReasonEQ applies the EQ predicate on the "branch_reason" field.
func BranchReasonEQ(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldBranchReason, v))
}

// BranchReasonNEQ applies the NEQ predicate on the "branch_reason" field.
func BranchReasonNEQ(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldBranchReason, v))
}

// BranchReasonIn applies the In predicate on the "branch_reason" field.
func BranchReasonIn(vs ...string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldBranchReason, vs...))
}

// BranchReasonNotIn applies the NotIn predicate on the "branch_reason" field.
func BranchReasonNotIn(vs ...string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldBranchReason, vs...))
}

// BranchReasonGT applies the GT predicate on the "branch_reason" field.
func BranchReasonGT(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldBranchReason, v))
}

// BranchReasonGTE applies the GTE predicate on the "branch_reason" field.
func BranchReasonGTE(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldBranchReason, v))
}

// BranchReasonLT applies the LT predicate on the "branch_reason" field.
func BranchReasonLT(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldBranchReason, v))
}

// BranchReasonLTE applies the LTE predicate on the "branch_reason" field.
func BranchReasonLTE(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldBranchReason, v))
}

// BranchReasonContains applies the Contains predicate on the "branch_reason" field.
func BranchReasonContains(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldContains(FieldBranchReason, v))
}

// BranchReasonHasPrefix applies the HasPrefix predicate on the "branch_reason" field.
func BranchReasonHasPrefix(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldHasPrefix(FieldBranchReason, v))
}

// BranchReasonHasSuffix applies the HasSuffix predicate on the "branch_reason" field.
func BranchReasonHasSuffix(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldHasSuffix(FieldBranchReason, v))
}

// BranchReasonEqualFold applies the EqualFold predicate on the "branch_reason" field.
func BranchReasonEqualFold(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEqualFold(FieldBranchReason, v))
}

// BranchReasonContainsFold applies the ContainsFold predicate on the "branch_reason" field.
func BranchReasonContainsFold(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldContainsFold(FieldBranchReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldCreatedAt, v))
}

// LastActiveAtEQ applies the EQ predicate on the "last_active_at" field.
func LastActiveAtEQ(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldEQ(FieldLastActiveAt, v))
}

// LastActiveAtNEQ applies the NEQ predicate on the "last_active_at" field.
func LastActiveAtNEQ(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNEQ(FieldLastActiveAt, v))
}

// LastActiveAtIn applies the In predicate on the "last_active_at" field.
func LastActiveAtIn(vs ...time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldIn(FieldLastActiveAt, vs...))
}

// LastActiveAtNotIn applies the NotIn predicate on the "last_active_at" field.
func LastActiveAtNotIn(vs ...time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldNotIn(FieldLastActiveAt, vs...))
}

// LastActiveAtGT applies the GT predicate on the "last_active_at" field.
func LastActiveAtGT(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGT(FieldLastActiveAt, v))
}

// LastActiveAtGTE applies the GTE predicate on the "last_active_at" field.
func LastActiveAtGTE(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldGTE(FieldLastActiveAt, v))
}

// LastActiveAtLT applies the LT predicate on the "last_active_at" field.
func LastActiveAtLT(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLT(FieldLastActiveAt, v))
}

// LastActiveAtLTE applies the LTE predicate on the "last_active_at" field.
func LastActiveAtLTE(v time.Time) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.FieldLTE(FieldLastActiveAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationBranch) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationBranch) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationBranch) predicate.ConversationBranch {
	return predicate.ConversationBranch(sql.NotPredicates(p))
}
