export default {
  researchGroup: {
    title: 'Research Group',
    description: 'Share one owner balance while every member keeps an independent account and API keys.',
    owner: { description: 'Fund members from your balance, set monthly limits, and review only the usage you paid for.' },
    status: { active: 'Active', paused: 'Paused', pending: 'Pending' },
    actions: { pauseGroup: 'Pause funding', resumeGroup: 'Resume funding', dissolve: 'Dissolve group', pause: 'Pause', resume: 'Resume', remove: 'Remove', leave: 'Leave group' },
    fields: { groupName: 'Group name', memberEmail: 'Exact registered email', monthlyLimit: 'Monthly limit (USD)' },
    stats: { sharedBalance: 'Shared balance', monthFunding: 'Funded this month', activeMembers: 'Active members', fundedRequests: 'Funded requests' },
    invite: { title: 'Invite a member', description: 'Only active, registered user accounts can be invited. The member must accept in their own account.', send: 'Send invitation', zeroLimitHint: 'A limit of $0 disables group funding and uses the member’s personal balance.' },
    members: { title: 'Members', description: 'Changing a limit does not reset usage already recorded this month.', empty: 'No members yet.', member: 'Member', usage: 'Monthly usage', resetAt: 'Resets at', reserved: '{amount} reserved by pending jobs' },
    usage: { title: 'Group-funded usage', description: 'Only requests paid from this group owner’s balance are visible here.', allMembers: 'All members', startDate: 'Start date', endDate: 'End date', empty: 'No group-funded requests match these filters.', model: 'Model', requestId: 'Request ID', cost: 'Paid cost', time: 'Time' },
    member: { owner: 'Funded by {owner}', limit: 'Monthly limit', used: 'Used', reserved: 'Reserved', remaining: 'Remaining', billingTitle: 'How your calls are billed', activeBilling: 'Eligible balance-based calls use the research group first. If its balance or your monthly allocation is unavailable, the entire call uses your personal balance.', pausedBilling: 'Group funding is paused. Balance-based calls currently use your personal balance.', zeroLimitBilling: 'Your group allocation is $0, so balance-based calls use your personal balance.', resetsAt: 'The monthly allocation resets at {date}.' },
    invitations: { title: 'Research group invitation', description: 'Accepting changes the first payer for eligible balance-based calls. Your account and API keys remain independent.', limit: 'Monthly funding limit: {amount}', accept: 'Accept', reject: 'Reject', accepted: 'Invitation accepted.', rejected: 'Invitation rejected.' },
    create: { title: 'Create a research group', description: 'Your balance becomes the shared funding source. Members remain separate users and keep control of their own API keys.', namePlaceholder: 'e.g. Computational Biology Lab', action: 'Create group' },
    dashboard: { invitationTitle: 'Research group invitation', invitationDescription: '{owner} invited you to {group}.', groupFunding: 'Research group funding', monthlyRemaining: 'Monthly remaining', usedOfLimit: '{used} used of {limit}', resetsAt: 'Resets {date}', personalBalance: 'Personal balance', fundingPriority: 'Group funding is used first; if unavailable, the full call falls back to your personal balance.', pausedFallback: 'Group funding is paused, so calls currently use your personal balance.', viewDetails: 'View group details' },
    messages: { created: 'Research group created.', updated: 'Group details updated.', paused: 'Group funding paused.', resumed: 'Group funding resumed.', invited: 'Invitation sent.', limitUpdated: 'Monthly limit updated.', memberPaused: 'Member funding paused.', memberResumed: 'Member funding resumed.', dissolved: 'Research group dissolved.', left: 'You left the research group.', usageReset: 'This month’s usage was reset.', removed: 'Member removed.' },
    confirm: { dissolveTitle: 'Dissolve research group?', dissolveMessage: 'All members will immediately return to personal balance billing. This cannot be undone.', leaveTitle: 'Leave research group?', leaveMessage: 'Future calls will use your personal balance. Your account and API keys are not removed.', resetTitle: 'Reset monthly usage?', resetMessage: 'Reset this month’s funded usage for {member}? This takes effect immediately.', removeTitle: 'Remove member?', removeMessage: 'Remove {member} from the group? Future calls will use their personal balance.' },
    errors: { operationFailed: 'Research group operation failed.', memberIneligible: 'This account cannot be added. Verify the exact email and account status.', alreadyAssigned: 'This account already belongs to a research group or has a pending invitation.', forbidden: 'You do not have permission to manage this research group.', bothBalancesInsufficient: 'Both the research group balance and personal balance are insufficient.' }
  }
}
