// Code generated by ent, DO NOT EDIT.

package conversationresponseref

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldUserID, v))
}

// ContextDomain applies equality check predicate on the "context_domain" field. It's identical to ContextDomainEQ.
func ContextDomain(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldContextDomain, v))
}

// ResponseIDHash applies equality check predicate on the "response_id_hash" field. It's identical to ResponseIDHashEQ.
func ResponseIDHash(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldResponseIDHash, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldSessionID, v))
}

// BranchID applies equality check predicate on the "branch_id" field. It's identical to BranchIDEQ.
func BranchID(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldBranchID, v))
}

// TailEventID applies equality check predicate on the "tail_event_id" field. It's identical to TailEventIDEQ.
func TailEventID(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldTailEventID, v))
}

// Durable applies equality check predicate on the "durable" field. It's identical to DurableEQ.
func Durable(v bool) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldDurable, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldUserID, v))
}

// ContextDomainEQ applies the EQ predicate on the "context_domain" field.
func ContextDomainEQ(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldContextDomain, v))
}

// ContextDomainNEQ applies the NEQ predicate on the "context_domain" field.
func ContextDomainNEQ(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldContextDomain, v))
}

// ContextDomainIn applies the In predicate on the "context_domain" field.
func ContextDomainIn(vs ...string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldContextDomain, vs...))
}

// ContextDomainNotIn applies the NotIn predicate on the "context_domain" field.
func ContextDomainNotIn(vs ...string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldContextDomain, vs...))
}

// ContextDomainGT applies the GT predicate on the "context_domain" field.
func ContextDomainGT(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldContextDomain, v))
}

// ContextDomainGTE applies the GTE predicate on the "context_domain" field.
func ContextDomainGTE(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldContextDomain, v))
}

// ContextDomainLT applies the LT predicate on the "context_domain" field.
func ContextDomainLT(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldContextDomain, v))
}

// ContextDomainLTE applies the LTE predicate on the "context_domain" field.
func ContextDomainLTE(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldContextDomain, v))
}

// ContextDomainContains applies the Contains predicate on the "context_domain" field.
func ContextDomainContains(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldContains(FieldContextDomain, v))
}

// ContextDomainHasPrefix applies the HasPrefix predicate on the "context_domain" field.
func ContextDomainHasPrefix(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldHasPrefix(FieldContextDomain, v))
}

// ContextDomainHasSuffix applies the HasSuffix predicate on the "context_domain" field.
func ContextDomainHasSuffix(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldHasSuffix(FieldContextDomain, v))
}

// ContextDomainEqualFold applies the EqualFold predicate on the "context_domain" field.
func ContextDomainEqualFold(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEqualFold(FieldContextDomain, v))
}

// ContextDomainContainsFold applies the ContainsFold predicate on the "context_domain" field.
func ContextDomainContainsFold(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldContainsFold(FieldContextDomain, v))
}

// ResponseIDHashEQ applies the EQ predicate on the "response_id_hash" field.
func ResponseIDHashEQ(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldResponseIDHash, v))
}

// ResponseIDHashNEQ applies the NEQ predicate on the "response_id_hash" field.
func ResponseIDHashNEQ(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldResponseIDHash, v))
}

// ResponseIDHashIn applies the In predicate on the "response_id_hash" field.
func ResponseIDHashIn(vs ...string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldResponseIDHash, vs...))
}

// ResponseIDHashNotIn applies the NotIn predicate on the "response_id_hash" field.
func ResponseIDHashNotIn(vs ...string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldResponseIDHash, vs...))
}

// ResponseIDHashGT applies the GT predicate on the "response_id_hash" field.
func ResponseIDHashGT(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldResponseIDHash, v))
}

// ResponseIDHashGTE applies the GTE predicate on the "response_id_hash" field.
func ResponseIDHashGTE(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldResponseIDHash, v))
}

// ResponseIDHashLT applies the LT predicate on the "response_id_hash" field.
func ResponseIDHashLT(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldResponseIDHash, v))
}

// ResponseIDHashLTE applies the LTE predicate on the "response_id_hash" field.
func ResponseIDHashLTE(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldResponseIDHash, v))
}

// ResponseIDHashContains applies the Contains predicate on the "response_id_hash" field.
func ResponseIDHashContains(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldContains(FieldResponseIDHash, v))
}

// ResponseIDHashHasPrefix applies the HasPrefix predicate on the "response_id_hash" field.
func ResponseIDHashHasPrefix(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldHasPrefix(FieldResponseIDHash, v))
}

// ResponseIDHashHasSuffix applies the HasSuffix predicate on the "response_id_hash" field.
func ResponseIDHashHasSuffix(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldHasSuffix(FieldResponseIDHash, v))
}

// ResponseIDHashEqualFold applies the EqualFold predicate on the "response_id_hash" field.
func ResponseIDHashEqualFold(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEqualFold(FieldResponseIDHash, v))
}

// ResponseIDHashContainsFold applies the ContainsFold predicate on the "response_id_hash" field.
func ResponseIDHashContainsFold(v string) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldContainsFold(FieldResponseIDHash, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldSessionID, v))
}

// BranchIDEQ applies the EQ predicate on the "branch_id" field.
func BranchIDEQ(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldBranchID, v))
}

// BranchIDNEQ applies the NEQ predicate on the "branch_id" field.
func BranchIDNEQ(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldBranchID, v))
}

// BranchIDIn applies the In predicate on the "branch_id" field.
func BranchIDIn(vs ...uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldBranchID, vs...))
}

// BranchIDNotIn applies the NotIn predicate on the "branch_id" field.
func BranchIDNotIn(vs ...uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldBranchID, vs...))
}

// BranchIDGT applies the GT predicate on the "branch_id" field.
func BranchIDGT(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldBranchID, v))
}

// BranchIDGTE applies the GTE predicate on the "branch_id" field.
func BranchIDGTE(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldBranchID, v))
}

// BranchIDLT applies the LT predicate on the "branch_id" field.
func BranchIDLT(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldBranchID, v))
}

// BranchIDLTE applies the LTE predicate on the "branch_id" field.
func BranchIDLTE(v uuid.UUID) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldBranchID, v))
}

// TailEventIDEQ applies the EQ predicate on the "tail_event_id" field.
func TailEventIDEQ(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldTailEventID, v))
}

// TailEventIDNEQ applies the NEQ predicate on the "tail_event_id" field.
func TailEventIDNEQ(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldTailEventID, v))
}

// TailEventIDIn applies the In predicate on the "tail_event_id" field.
func TailEventIDIn(vs ...int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldTailEventID, vs...))
}

// TailEventIDNotIn applies the NotIn predicate on the "tail_event_id" field.
func TailEventIDNotIn(vs ...int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldTailEventID, vs...))
}

// TailEventIDGT applies the GT predicate on the "tail_event_id" field.
func TailEventIDGT(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldTailEventID, v))
}

// TailEventIDGTE applies the GTE predicate on the "tail_event_id" field.
func TailEventIDGTE(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldTailEventID, v))
}

// TailEventIDLT applies the LT predicate on the "tail_event_id" field.
func TailEventIDLT(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldTailEventID, v))
}

// TailEventIDLTE applies the LTE predicate on the "tail_event_id" field.
func TailEventIDLTE(v int64) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldTailEventID, v))
}

// TailEventIDIsNil applies the IsNil predicate on the "tail_event_id" field.
func TailEventIDIsNil() predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIsNull(FieldTailEventID))
}

// TailEventIDNotNil applies the NotNil predicate on the "tail_event_id" field.
func TailEventIDNotNil() predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotNull(FieldTailEventID))
}

// DurableEQ applies the EQ predicate on the "durable" field.
func DurableEQ(v bool) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldDurable, v))
}

// DurableNEQ applies the NEQ predicate on the "durable" field.
func DurableNEQ(v bool) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldDurable, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationResponseRef) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationResponseRef) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationResponseRef) predicate.ConversationResponseRef {
	return predicate.ConversationResponseRef(sql.NotPredicates(p))
}
