// Code generated by ent, DO NOT EDIT.

package researchgroupmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the researchgroupmember type in the database.
	Label = "research_group_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResearchGroupID holds the string denoting the research_group_id field in the database.
	FieldResearchGroupID = "research_group_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMonthlyLimitUsd holds the string denoting the monthly_limit_usd field in the database.
	FieldMonthlyLimitUsd = "monthly_limit_usd"
	// FieldMonthlyUsageUsd holds the string denoting the monthly_usage_usd field in the database.
	FieldMonthlyUsageUsd = "monthly_usage_usd"
	// FieldMonthlyReservedUsd holds the string denoting the monthly_reserved_usd field in the database.
	FieldMonthlyReservedUsd = "monthly_reserved_usd"
	// FieldUsageWindowStart holds the string denoting the usage_window_start field in the database.
	FieldUsageWindowStart = "usage_window_start"
	// FieldInvitedAt holds the string denoting the invited_at field in the database.
	FieldInvitedAt = "invited_at"
	// FieldAcceptedAt holds the string denoting the accepted_at field in the database.
	FieldAcceptedAt = "accepted_at"
	// FieldPausedAt holds the string denoting the paused_at field in the database.
	FieldPausedAt = "paused_at"
	// FieldRemovedAt holds the string denoting the removed_at field in the database.
	FieldRemovedAt = "removed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeResearchGroup holds the string denoting the research_group edge name in mutations.
	EdgeResearchGroup = "research_group"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the researchgroupmember in the database.
	Table = "research_group_members"
	// ResearchGroupTable is the table that holds the research_group relation/edge.
	ResearchGroupTable = "research_group_members"
	// ResearchGroupInverseTable is the table name for the ResearchGroup entity.
	// It exists in this package in order to avoid circular dependency with the "researchgroup" package.
	ResearchGroupInverseTable = "research_groups"
	// ResearchGroupColumn is the table column denoting the research_group relation/edge.
	ResearchGroupColumn = "research_group_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "research_group_members"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for researchgroupmember fields.
var Columns = []string{
	FieldID,
	FieldResearchGroupID,
	FieldUserID,
	FieldStatus,
	FieldMonthlyLimitUsd,
	FieldMonthlyUsageUsd,
	FieldMonthlyReservedUsd,
	FieldUsageWindowStart,
	FieldInvitedAt,
	FieldAcceptedAt,
	FieldPausedAt,
	FieldRemovedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultMonthlyLimitUsd holds the default value on creation for the "monthly_limit_usd" field.
	DefaultMonthlyLimitUsd float64
	// DefaultMonthlyUsageUsd holds the default value on creation for the "monthly_usage_usd" field.
	DefaultMonthlyUsageUsd float64
	// DefaultMonthlyReservedUsd holds the default value on creation for the "monthly_reserved_usd" field.
	DefaultMonthlyReservedUsd float64
	// DefaultUsageWindowStart holds the default value on creation for the "usage_window_start" field.
	DefaultUsageWindowStart func() time.Time
	// DefaultInvitedAt holds the default value on creation for the "invited_at" field.
	DefaultInvitedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ResearchGroupMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResearchGroupID orders the results by the research_group_id field.
func ByResearchGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResearchGroupID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMonthlyLimitUsd orders the results by the monthly_limit_usd field.
func ByMonthlyLimitUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyLimitUsd, opts...).ToFunc()
}

// ByMonthlyUsageUsd orders the results by the monthly_usage_usd field.
func ByMonthlyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyUsageUsd, opts...).ToFunc()
}

// ByMonthlyReservedUsd orders the results by the monthly_reserved_usd field.
func ByMonthlyReservedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyReservedUsd, opts...).ToFunc()
}

// ByUsageWindowStart orders the results by the usage_window_start field.
func ByUsageWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageWindowStart, opts...).ToFunc()
}

// ByInvitedAt orders the results by the invited_at field.
func ByInvitedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvitedAt, opts...).ToFunc()
}

// ByAcceptedAt orders the results by the accepted_at field.
func ByAcceptedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptedAt, opts...).ToFunc()
}

// ByPausedAt orders the results by the paused_at field.
func ByPausedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPausedAt, opts...).ToFunc()
}

// ByRemovedAt orders the results by the removed_at field.
func ByRemovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemovedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByResearchGroupField orders the results by research_group field.
func ByResearchGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResearchGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newResearchGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResearchGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ResearchGroupTable, ResearchGroupColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
